### PR TITLE
fix(windows): keep the main loop running even if a request has an error

### LINKED ISSUE #3521: windows: Remove any unnecessary unwraps / bails
**Describe the bug**
There are some cases in the code where I didn't write proper error handling yet, and the main loop will either panic on `unwrap` or bail with a `?` operator, even though the error could be handled or logged and then ignored.

**To Reproduce**
`git grep unwrap`

**Expected behavior**
Expect the main loop in `run_controller` to keep running unless it hits an error it can't recover from by itself.

**Screenshots / Logs**
N/A

**Platform (please complete the following information):**
 - Firezone Version: N/A
 - OS: Windows, any

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by ReactorScram**
Closes #3521 because now almost all of the `?` in the main loop will log an error and not bail. This is nice for trivial things like copying a resource when we're not signed in. (e.g. User opens the menu, the token expires, user clicks something, it should just do nothing instead of crashing)

Closes a long-standing TODO for moving more of the request handling code inside `impl Controller`

### CODE REVIEW

**Comment by ReactorScram** [comment]
@jamilbk I don't remember which direction we agreed to go - Bail on anything so the app doesn't keep running in a possibly bad state, or try to log and handle errors?

This PR pushes it more towards, "Log and move on"

**Comment by jamilbk** [comment]
@ReactorScram The client shouldn't need to handle most of these kinds of edge cases:

> e.g. User opens the menu, the token expires

The portal should have disconnected us, which connlib will try to reconnect, receive a `401`, and then call `on_disconnect(errorString)`. There's a small window of time you could copy a resource, but I think that's fine, just let the user copy it. By the time they go to paste it and try to access it, the client will have signed them out and dispatched a UI notification.

Ideally, the more we can rely on state management from connlib, the better. The UI just becomes a puppet to the state updates emitted by connlib. #3343 

That said, generally, I do think "Log it and move on" is better. Ideally always keeping the token around unless we explicitly receive `on_disconnect(errorString)`

**Comment by ReactorScram** [comment]
Yeah. There's just a shocking number of `expect` and `?` floating around the Windows client, mostly file I/O. IME these are things that will never fail until they're running on the worst possible system with failing RAM or a dying HDD and then we'll want the logs to say "Looks like an OS / hardware bug, not our problem"

**Comment by jamilbk** [comment]
Ah, I see where you're coming from now.

Yeah, the way @roop approached this is to fail gracefully in the case of disk I/O errors. It may not be as crucial for the user-facing clients, but in headless mode, you may need Firezone running to remotely access the machine to e.g. free up disk space. If we can avoid crashing for log writing, `firezone-id` saves, and `actor_name` saves, that might be good. If it adds a lot of complexity though, let's punt the ball down the field for later (sorry, Super bowl reference)

I'm not sure if we can avoid it for saving the token too, that one might just be a show stopper

**Review by conectado — APPROVED** [review]
lgtm

**Review by jamilbk — APPROVED** [review]

**Pull request merged**
