### PR TITLE
fix(connlib): use quinn fork for quinn to work on ios

### LINKED ISSUE #4276: "Connection failed, no candidates received" on iOS device with IPv4 only.
Experienced by @bmanifold on his iPhone which has IPv4 only (may or may not be a factor).

Suspected gateway logs:

```
2024-03-22T19:45:36.453745Z  INFO Eventloop::poll:accept_connection{id=38678f68-3cda-4add-87b2-82c0483e1d0f}: str0m::ice_::agent: State change (new connection): New -> Checking
2024-03-22T19:45:36.454241Z  INFO Eventloop::poll:accept_connection{id=38678f68-3cda-4add-87b2-82c0483e1d0f}: snownet::node: Created new connection
2024-03-22T19:45:36.454796Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:2226555494660524928 1 udp 2130706175 172.17.0.2 51970 typ host
2024-03-22T19:45:36.456962Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:2338719037163789452 1 udp 2130706431 fd00::242:ac11:2 43490 typ host
2024-03-22T19:45:36.457030Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:3329374309411154963 1 udp 1694498559 3.231.55.21 51970 typ srflx
2024-03-22T19:45:36.457071Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:2845229780322257096 1 udp 50331391 34.148.168.108 51256 typ relay
2024-03-22T19:45:36.457149Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:11011284213101745836 1 udp 50331647 2600:1900:4020:eb:0:12:: 51256 typ relay
2024-03-22T19:45:36.457201Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:17296116321717390924 1 udp 1694498815 2600:1f18:2406:c402:7066:4674:38e7:efd3 43490 typ srflx
2024-03-22T19:45:36.457252Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:1556540688565005902 1 udp 50331391 34.151.248.99 57195 typ relay
2024-03-22T19:45:36.457327Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:14935958210108877476 1 udp 50331647 2600:1900:40f0:e339:0:13:: 57195 typ relay
2024-03-22T19:45:36.457384Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:1556540688565005902 1 udp 50331391 34.151.248.99 59404 typ relay
2024-03-22T19:45:36.457418Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:14935958210108877476 1 udp 50331647 2600:1900:40f0:e339:0:13:: 59404 typ relay
2024-03-22T19:45:36.457470Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:2845229780322257096 1 udp 50331391 34.148.168.108 55033 typ relay
2024-03-22T19:45:36.457503Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:11011284213101745836 1 udp 50331647 2600:1900:4020:eb:0:12:: 55033 typ relay
2024-03-22T19:45:36.457524Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:14158577346473663653 1 udp 50331391 34.87.223.207 64435 typ relay
2024-03-22T19:45:36.457591Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:11970412396909905767 1 udp 50331647 2600:1900:40b0:1504:0:12:: 64435 typ relay
2024-03-22T19:45:36.457643Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:2077113276712493812 1 udp 50331391 34.102.20.7 49759 typ relay
2024-03-22T19:45:36.457675Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:4628041249016130852 1 udp 50331647 2600:1900:4120:f732:0:12:: 49759 typ relay
2024-03-22T19:45:36.457697Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:14158577346473663653 1 udp 50331391 34.87.223.207 63547 typ relay
2024-03-22T19:45:36.457749Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:11970412396909905767 1 udp 50331647 2600:1900:40b0:1504:0:12:: 63547 typ relay
2024-03-22T19:45:36.457771Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:2077113276712493812 1 udp 50331391 34.102.20.7 52854 typ relay
2024-03-22T19:45:36.457813Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:4628041249016130852 1 udp 50331647 2600:1900:4120:f732:0:12:: 52854 typ relay
2024-03-22T19:45:36.457842Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:17303496149634970361 1 udp 50331391 35.194.2.239 56845 typ relay
2024-03-22T19:45:36.457863Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:3436115692907268846 1 udp 50331647 2600:1900:4000:102d:0:12:: 56845 typ relay
2024-03-22T19:45:36.457908Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:17303496149634970361 1 udp 50331391 35.194.2.239 61089 typ relay
2024-03-22T19:45:36.457939Z DEBUG Eventloop::poll: firezone_gateway::eventloop: Sending ICE candidate to client client=38678f68-3cda-4add-87b2-82c0483e1d0f candidate=candidate:3436115692907268846 1 udp 50331647 2600:1900:4000:102d:0:12:: 61089 typ relay
2024-03-22T19:45:36.483287Z  INFO Eventloop::poll:decapsulate{from=34.148.168.108:3478 num_bytes=28}:handle_input{id=TransactionId(0x09E8F00F8BBA786FCFAE1F86) method=refresh class=success response rtt=34.413092ms}: snownet::allocation: Updated lifetime of allocation srflx=Some(Candidate(srflx=3.231.55.21:51970/udp base=172.17.0.2:51970 prio=1694498559)) relay_ip4=Some(Candidate(relay=34.148.168.108:51256/udp prio=50331391)) relay_ip6=Some(Candidate(relay=[2600:1900:4020:eb:0:12::]:51256/udp prio=50331647)) lifetime=Lifetime(600s)
2024-03-22T19:45:36.483347Z  INFO Eventloop::poll:decapsulate{from=[2600:1900:4020:eb:0:12::]:3478 num_bytes=28}:handle_input{id=TransactionId(0x6590F9DAF516E699DA478D27) method=refresh class=success response rtt=34.500816ms}: snownet::allocation: Updated lifetime of allocation srflx=Some(Candidate(srflx=[2600:1f18:2406:c402:7066:4674:38e7:efd3]:43490/udp base=[fd00::242:ac11:2]:43490 prio=1694498815)) relay_ip4=Some(Candidate(relay=34.148.168.108:55033/udp prio=50331391)) relay_ip6=Some(Candidate(relay=[2600:1900:4020:eb:0:12::]:55033/udp prio=50331647)) lifetime=Lifetime(600s)
2024-03-22T19:45:36.487951Z  INFO Eventloop::poll:decapsulate{from=35.194.2.239:3478 num_bytes=28}:handle_input{id=TransactionId(0xB30B68B3E5D561653AEA6B5E) method=refresh class=success response rtt=39.07751ms}: snownet::allocation: Updated lifetime of allocation srflx=Some(Candidate(srflx=3.231.55.21:51970/udp base=172.17.0.2:51970 prio=1694498559)) relay_ip4=Some(Candidate(relay=35.194.2.239:61089/udp prio=50331391)) relay_ip6=Some(Candidate(relay=[2600:1900:4000:102d:0:12::]:61089/udp prio=50331647)) lifetime=Lifetime(600s)
2024-03-22T19:45:36.490775Z  INFO Eventloop::poll:decapsulate{from=[2600:1900:4000:102d:0:12::]:3478 num_bytes=28}:handle_input{id=TransactionId(0xA188BC0A486A6557A2B468FD) method=refresh class=success response rtt=41.915484ms}: snownet::allocation: Updated lifetime of allocation srflx=Some(Candidate(srflx=[2600:1f18:2406:c402:7066:4674:38e7:efd3]:43490/udp base=[fd00::242:ac11:2]:43490 prio=1694498815)) relay_ip4=Some(Candidate(relay=35.194.2.239:56845/udp prio=50331391)) relay_ip6=Some(Candidate(relay=[2600:1900:4000:102d:0:12::]:56845/udp prio=50331647)) lifetime=Lifetime(600s)
2024-03-22T19:45:36.524227Z  INFO Eventloop::poll:decapsulate{from=34.102.20.7:3478 num_bytes=28}:handle_input{id=TransactionId(0xD96E48C75ECCBFA19841F882) method=refresh class=success response rtt=75.350768ms}: snownet::allocation: Updated lifetime of allocation srflx=Some(Candidate(srflx=3.231.55.21:51970/udp base=172.17.0.2:51970 prio=1694498559)) relay_ip4=Some(Candidate(relay=34.102.20.7:49759/udp prio=50331391)) relay_ip6=Some(Candidate(relay=[2600:1900:4120:f732:0:12::]:49759/udp prio=50331647)) lifetime=Lifetime(600s)
2024-03-22T19:45:36.525830Z  INFO Eventloop::poll:decapsulate{from=[2600:1900:4120:f732:0:12::]:3478 num_bytes=28}:handle_input{id=TransactionId(0xF0FBDA93D31800C1A8C200C1) method=refresh class=success response rtt=76.960849ms}: snownet::allocation: Updated lifetime of allocation srflx=Some(Candidate(srflx=[2600:1f18:2406:c402:7066:4674:38e7:efd3]:43490/udp base=[fd00::242:ac11:2]:43490 prio=1694498815)) relay_ip4=Some(Candidate(relay=34.102.20.7:52854/udp prio=50331391)) relay_ip6=Some(Candidate(relay=[2600:1900:4120:f732:0:12::]:52854/udp prio=50331647)) lifetime=Lifetime(600s)
2024-03-22T19:45:36.575688Z  INFO Eventloop::poll:decapsulate{from=34.151.248.99:3478 num_bytes=28}:handle_input{id=TransactionId(0x6B963F720F28CE1FFC82BE9F) method=refresh class=success response rtt=126.81214ms}: snownet::allocation: Updated lifetime of allocation srflx=Some(Candidate(srflx=3.231.55.21:51970/udp base=172.17.0.2:51970 prio=1694498559)) relay_ip4=Some(Candidate(relay=34.151.248.99:59404/udp prio=50331391)) relay_ip6=Some(Candidate(relay=[2600:1900:40f0:e339:0:13::]:59404/udp prio=50331647)) lifetime=Lifetime(600s)
2024-03-22T19:45:36.577805Z  INFO Eventloop::poll:decapsulate{from=[2600:1900:40f0:e339:0:13::]:3478 num_bytes=28}:handle_input{id=TransactionId(0xB9F18ADA079332E23CD67887) method=refresh class=success response rtt=128.932041ms}: snownet::allocation: Updated lifetime of allocation srflx=Some(Candidate(srflx=[2600:1f18:2406:c402:7066:4674:38e7:efd3]:43490/udp base=[fd00::242:ac11:2]:43490 prio=1694498815)) relay_ip4=Some(Candidate(relay=34.151.248.99:57195/udp prio=50331391)) relay_ip6=Some(Candidate(relay=[2600:1900:40f0:e339:0:13::]:57195/udp prio=50331647)) lifetime=Lifetime(600s)
2024-03-22T19:45:36.656795Z  INFO Eventloop::poll:decapsulate{from=34.87.223.207:3478 num_bytes=28}:handle_input{id=TransactionId(0x2E99983039BAB9CE42996A6F) method=refresh class=success response rtt=207.920341ms}: snownet::allocation: Updated lifetime of allocation srflx=Some(Candidate(srflx=3.231.55.21:51970/udp base=172.17.0.2:51970 prio=1694498559)) relay_ip4=Some(Candidate(relay=34.87.223.207:64435/udp prio=50331391)) relay_ip6=Some(Candidate(relay=[2600:1900:40b0:1504:0:12::]:64435/udp prio=50331647)) lifetime=Lifetime(600s)
2024-03-22T19:45:36.656956Z  INFO Eventloop::poll:decapsulate{from=[2600:1900:40b0:1504:0:12::]:3478 num_bytes=28}:handle_input{id=TransactionId(0x26ED6990C274695329A4329A) method=refresh class=success response rtt=208.07941ms}: snownet::allocation: Updated lifetime of allocation srflx=Some(Candidate(srflx=[2600:1f18:2406:c402:7066:4674:38e7:efd3]:43490/udp base=[fd00::242:ac11:2]:43490 prio=1694498815)) relay_ip4=Some(Candidate(relay=34.87.223.207:63547/udp prio=50331391)) relay_ip6=Some(Candidate(relay=[2600:1900:40b0:1504:0:12::]:63547/udp prio=50331647)) lifetime=Lifetime(600s)
2024-03-22T19:45:36.804461Z DEBUG Eventloop::poll:handle_timeout{id=cff40cf5-0ff9-4445-8876-3655942a3b4a}: boringtun::noise::timers: KEEPALIVE(PERSISTENT_KEEPALIVE)
2024-03-22T19:45:41.788390Z DEBUG Eventloop::poll:handle_timeout{id=e5732f6c-3f4a-46d1-a266-1b403cf3b9e2}: boringtun::noise::timers: KEEPALIVE(PERSISTENT_KEEPALIVE)
2024-03-22T19:45:46.450093Z  INFO Eventloop::poll:handle_timeout{id=38678f68-3cda-4add-87b2-82c0483e1d0f}: snownet::node: Connection failed (no candidates received)
2024-03-22T19:45:46.804593Z DEBUG Eventloop::poll:handle_timeout{id=cff40cf5-0ff9-4445-8876-3655942a3b4a}: boringtun::noise::timers: KEEPALIVE(PERSISTENT_KEEPALIVE)
2024-03-22T19:45:47.213546Z DEBUG Eventloop::poll:handle_timeout{id=f14aab87-2d08-4f02-b8be-251fc93f1c2c}: boringtun::noise::timers: SESSION_EXPIRED(REJECT_AFTER_TIME) session=1951473409
2024-03-22T19:45:47.213575Z DEBUG Eventloop::poll:handle_timeout{id=f14aab87-2d08-4f02-b8be-251fc93f1c2c}: boringtun::noise::timers: KEEPALIVE(PERSISTENT_KEEPALIVE)
```

### PR DESCRIPTION
**Pull request by conectado**
Fixes #4276 
WIP

### CODE REVIEW

**Review by jamilbk — APPROVED** [review]
This fixes it! Works great on IPv4-only iOS.

**Comment by jamilbk** [comment]
@conectado You missed one I think on 51:

```
impl UdpSocketState {
    pub fn new(sock: UdpSockRef<'_>) -> io::Result<Self> {
        let io = sock.0;
        let mut cmsg_platform_space = 0;
        if cfg!(target_os = "linux")
            || cfg!(target_os = "freebsd")
            || cfg!(target_os = "macos")
            || cfg!(target_os = "ios")
            || cfg!(target_os = "android")
        {
            cmsg_platform_space +=
                unsafe { libc::CMSG_SPACE(mem::size_of::<libc::in6_pktinfo>() as _) as usize };
        }

```

**Comment by jamilbk** [comment]
@conectado See https://github.com/quinn-rs/quinn/compare/main...firezone:quinn:main

**Comment by conectado** [comment]
@jamilbk changing this branch to `firezone` fork instead of my own :)

**Comment by conectado** [comment]
Opening this up since it was tested

**Review by jamilbk — APPROVED** [review]

**Comment by jamilbk** [comment]
@conectado I think this PR updated _all_ dependencies and pulled in something that's now causing a panic on macOS. See #4281 

Still triaging...

**Comment by jamilbk** [comment]
Ah yeah, there was an order of operations error in this fork -- fixed here: https://github.com/quinn-rs/quinn/commit/248ac33ff79ba3173e794aa63cc814d70f4714b3

**Pull request merged**
