### PR TITLE
chore: pre-commit `cargo fmt`

### PR DESCRIPTION
**Pull request by ReactorScram**
Found from here https://pre-commit.com/hooks.html

I keep forgetting to run fmt by hand.

### CODE REVIEW

**Review by jamilbk — COMMENTED** [review]
Is this redundant with the equivalent check in `.github/workflows/_rust.yml`? If so maybe it's worth removing that one?

Any idea whether this is platform-specific or applies to all platforms? I noticed the check we have in _rust.yml runs on each platform.

**Comment by ReactorScram** [comment]
@jamilbk This is intended for running `pre-commit` locally before making commits. I'm not sure how the Gabi and Thomas are doing it on their machines, maybe if they use rust-analyzer it has some setting to auto-format? 🤔 But on my setup with no LSP and a relatively dumb editor, I am constantly forgetting to run `fmt` before committing and pushing.

With this patch it catches on my machine instead of doing a CI iteration.

**Comment by jamilbk** [comment]
@ReactorScram I think we're all using editors with native linting/fixing integration (vim/code/emacs) which seems pretty common these days. (I'm also using fix-on-save for elixir/swift/kotlin/markdown/typescript).

I'm afraid this is probably better suited to your local environment than adding as a redundant CI check -- try configuring a local `.pre-commit.config.yaml` for your dev setup in `$HOME` perhaps and specifying it with `pre-commit install --config` to set it up.

**Comment by jamilbk** [comment]
Side quest: writing an LSP integration for Kate? 😄

**Comment by jamilbk** [comment]
(We use pre-commit in CI for global linting that's not handled well by language-specific things like codespell etc)

**Comment by ReactorScram** [comment]
Okay well it should say in the docs what YAML to use then, or other contributors will have to dig it out when CI runs fail

I can barely get Python to run on Windows on a good day.... It's not working on either of my envs at the moment anyway, only on Linux and maybe macOS.

**Comment by ReactorScram** [comment]
Like I'm not intending to add this to CI, I put it in because that causes my env to pick it up automatically.

Did you guys all manually configure this stuff in your different editors?

**Comment by jamilbk** [comment]
> Okay well it should say in the docs what YAML to use then

Hmm yeah, that makes sense. Getting all of the linting to run for all languages inside a single pre-commit is tough, we started like that but voted on the system we have now because of the Python dependency/overhead, and if we did that you would need all runtimes setup on your dev machine.

Maybe this is better suited as a snippet in docs/CONTRIBUTING.md or a separate YAML config?

> Did you guys all manually configure this stuff in your different editors?

Yeah, but it's not that bad -- we generally just use the "standard" style for most languages. I think `rustfmt` handles it for Rust. Here's my editor config if it's helpful: https://github.com/jamilbk/nvim/blob/master/init.vim#L141

**Pull request closed without merging**
