### PR TITLE
chore(clients): output human-formatted logs in addition to JSON

### PR DESCRIPTION
**Pull request by thomaseizinger**
Currently, the clients only send JSON formatted logs to the configured log directory. These are very hard to read as a human because one has to re-assemble the spans and fields that we use extensively in connlib's logs.

With this patch, the logs are sent to two files: `.jsonl` as JSON formatted and `.log` formatted in syslog format.

### CODE REVIEW

**Review by jamilbk — COMMENTED** [review]
I think we probably just want to choose `syslog` format to avoid wasting disk space for duplicate logs. What do you think?

**Comment by thomaseizinger** [comment]
> I think we probably just want to choose `syslog` format to avoid wasting disk space for duplicate logs. What do you think?

Works for me, I just want non-JSON logs. Whatever gets us the fastest consensus so we can merge it is fine for me :)

**Review by jamilbk — APPROVED** [review]
Looks fine by me (pending removal of the double-logging with JSONL for clients) but I would be curious to hear any objections from @ReactorScram.

Also, just double-checking, does the syslog format print timestamp as the first column?

**Comment by thomaseizinger** [comment]
> Also, just double-checking, does the syslog format print timestamp as the first column?

Yes, it is:

- ISO8601 timestamp
- level
- spans
- module
- message

For example:

image

**Review by ReactorScram — APPROVED** [review]
Yeah it's fine. If I ever need machine-readable logs for a test or something, mind if I add a `--jsonl-logs` flag that turns JSONL back on in addition to syslog?

So far I haven't bothered parsing the JSONL logs so we can get rid of them under YAGNI

**Comment by thomaseizinger** [comment]
> mind if I add a `--jsonl-logs` flag that turns JSONL back on in addition to syslog?

They are still there in the log files, same as currently! What this PR is doing is emitting and additional log file!

**Pull request merged**
