### PR TITLE
fix(windows): Ensure production exes / MSIs don't show "-modified" Git versions

### LINKED ISSUE #3384: bug(windows): Git version is always `-modified`
**Describe the bug**
The About dialog always says the build is from modified code and not direct from Git.

**To Reproduce**
Download an MSI from a CI run, install it, run it, open the About dialog. The Git version will always have "-modified" at the end even though that is intended for dev builds, not CI runs.

**Expected behavior**
Expect dev builds with modified files to have `-modified` but CI builds to not have that.

**Screenshots / Logs**
image

**Platform (please complete the following information):**
 - Firezone Version 9e81
 - OS: Windows 11

**Additional context**
Found while working on #3382

~~We can probably fix this by moving the `git_version!` macro call out of the main code and into `build.rs`, then having `build.rs` invoke all the frontend build stuff like copying flowbite, building TS, and building Tailwind after the Git version is already captured.~~

Update: It's actually not related to the frontend build. I'm running a CI probe now

This is kind of a big "Spend all day fighting CI" change so I don't think it's worth intermixing with any important work. It can probably wait until after beta.

### PR DESCRIPTION
**Pull request by ReactorScram**
Fixes #3384

### CODE REVIEW

**Comment by ReactorScram** [comment]
Might be some intended Tauri behavior, asked them here https://github.com/tauri-apps/tauri/issues/8711

**Comment by ReactorScram** [comment]
Finally got it. Jamil was right, it was the line endings in the checkout action.

image

**Review by jamilbk — APPROVED** [review]
Good catch! I suspected it was something weird with line endings

**Comment by ReactorScram** [comment]
Hope everyone else is okay with that `.gitattributes` file btw. It should disable any clever CRLF / LF conversions Git tries to do for Windows. Hopefully on Mac / Linux it won't have any effect. 

My Kate config is already set to use LF endings by default.

**Pull request merged**
