### PR TITLE
Add guide for restricting SSO to VPN users

### PR DESCRIPTION
**Pull request by gongjason**

### CODE REVIEW

**Comment by jamilbk** [comment]
I'm a bit confused -- is this for restricting SSO *after* the user connects VPN? Wouldn't he/she need to... auth via SSO to connect to VPN first? Seems like a chicken-and-egg?

**Comment by gongjason** [comment]
> I'm a bit confused -- is this for restricting SSO _after_ the user connects VPN? Wouldn't he/she need to... auth via SSO to connect to VPN first? Seems like a chicken-and-egg?

You can set the restriction on an app basis (so you could exclude Firezone). The main purpose is to restrict SSO for other apps. Though I suppose if someone leaked their IdP credentials, the threat actor could also get access to the VPN if it's also using the same IdP for SSO...

Was looking into this after a customer brought it up. Their purpose was to ensure everyone has the VPN on when accessing their cloud apps.

**Comment by jamilbk** [comment]
Ah. I see -- an application of the `NAT Gateway` / `Whitelisting` guide. Hm ok, may want to organize them together.

**Comment by jamilbk** [comment]
Good idea to update the index for the user guides? https://github.com/firezone/firezone/tree/add-sso-on-vpn/docs/docs#common-configuration-guides

**Comment by gongjason** [comment]
Moved to https://github.com/firezone/firezone/pull/1185

**Pull request closed without merging**
