### PR TITLE
feat!(portal): return relays as plain socket addresses

### PR DESCRIPTION
**Pull request by thomaseizinger**
Extracted out of #3391.

We don't actually need this for #3391 though because we've added a compatibility layer during deserialization. But, it will be good to remove that compat layer at some point which means we have to return the addresses as plain socket addresses. Because that is a breaking change, I decided to extract this into a different PR.

Co-authored-by: conectado <gabrielalejandro7@gmail.com>

### CODE REVIEW

**Comment by thomaseizinger** [comment]
This will fail CI until we merge #3391 but can be merged any time after.

**Comment by conectado** [comment]
Should we remove the compatibility layer as part of this PR?

**Comment by thomaseizinger** [comment]
> Should we remove the compatibility layer as part of this PR?

I guess we could because from that point onward, the old format will never be returned again.

**Review by AndrewDryga — APPROVED** [review]

**Comment by AndrewDryga** [comment]
👍 for removing the compatibility layer in the rust too. And acceptance tests fail for some reason..

**Review by conectado — APPROVED** [review]
we can merge this now :)

**Comment by conectado** [comment]
> 👍 for removing the compatibility layer in the rust too. And acceptance tests fail for some reason..

we need to update the field naming in rust too, will push a fix

**Review by thomaseizinger — COMMENTED** [review]
ACK the rust changes

**Pull request merged**
