### PR TITLE
Make OIDC and SAML user provisioning configurable per-provider

### PR DESCRIPTION
**Pull request by jamilbk**
Fixes firezone/product#485

### CODE REVIEW

**Comment by akrousset** [comment]
👍 

The migration is at least easy to follow w/ Elixir. I think the trickiest part is the jsonb_insert (had to look up the docs on that one). 

Only one thing: The docs should be updated to include this new field. I wasn't sure if that was going to be on the other PR or this one.

**Comment by jamilbk** [comment]
> 👍
> 
> The migration is at least easy to follow w/ Elixir. I think the trickiest part is the jsonb_insert (had to look up the docs on that one).
> 
> Only one thing: The docs should be updated to include this new field. I wasn't sure if that was going to be on the other PR or this one.

Yeah I'm sure there's a way I could have done it all in SQL but after spending an hour noodling on it I couldn't figure it out (and Google wasn't helpful).

What docs were you thinking of? This will go into the REST API docs for 0.7.0 (we are pushing the API till next release).

**Comment by akrousset** [comment]
> What docs were you thinking of? This will go into the REST API docs for 0.7.0 (we are pushing the API till next release).

Oh I was thinking of the authentication docs for each provider where we provide a sample JSON config like [here](https://docs.firezone.dev/authenticate/okta#integrate-with-firezone).

**Comment by jamilbk** [comment]
> > What docs were you thinking of? This will go into the REST API docs for 0.7.0 (we are pushing the API till next release).
> 
> Oh I was thinking of the authentication docs for each provider where we provide a sample JSON config like [here](https://docs.firezone.dev/authenticate/okta#integrate-with-firezone).

Ah, yeah let me make sure those are current.

**Pull request merged**
