### PR TITLE
fix(relay): fix otel endpoint type

### PR DESCRIPTION
**Pull request by Intuinewin**
Completely forgot this https://github.com/firezone/firezone/issues/3251

This is the PR you asked for :/

### CODE REVIEW

**Comment by jamilbk** [comment]
> Completely forgot this https://github.com/firezone/firezone/issues/3251
> 
> 
> 
> This is the PR you asked for :/

Thanks for the contribution!

**Comment by thomaseizinger** [comment]
Can you add a test using https://docs.rs/clap/latest/clap/trait.Parser.html#method.try_parse_from that ensures we accept a DNS name? I am worried that if we don't have a test for this, we will forget about this requirement and change it back to a socket address or something else in a refactoring.

**Comment by Intuinewin** [comment]
Rebased with a test !

**Review by thomaseizinger — APPROVED** [review]
Thanks!

Unfortunately our CI is not optimised for contributions from forks yet so I am going to take your commit and push it to a local branch and merge it from there. The attribution should stay in-tact through that!

**Comment by thomaseizinger** [comment]
Replaced by https://github.com/firezone/firezone/pull/5059.

**Comment by jamilbk** [comment]
> Thanks!
> 
> 
> 
> Unfortunately our CI is not optimised for contributions from forks yet so I am going to take your commit and push it to a local branch and merge it from there. The attribution should stay in-tact through that!

Another option is changing the base of this PR to a contrib branch, open a Pr with that, then merging.

That'll prevent having to close unmerged PRs

**Comment by thomaseizinger** [comment]
Ah that is a good idea! I'll do that next time!

**Pull request closed without merging**
