### PR TITLE
fix(relay): reuse `delete_allocation` function

### PR DESCRIPTION
**Pull request by thomaseizinger**
Previously, we would access the state around allocations from different places. This actually led to a minor memory leak where we wouldn't clean up the `allocations_by_port` table. We refactor the code slightly to avoid this.

### CODE REVIEW

**Review by conectado — APPROVED** [review]

**Comment by jamilbk** [comment]
Hopefully #1748 fixes the status check saga. Maybe @conectado can resolve the conflict if everything looks good?

**Comment by thomaseizinger** [comment]
@AndrewDryga Just had a failing unit elixir unit test as part of the merge queue: https://github.com/firezone/firezone/actions/runs/5499494847/jobs/10021734312. Perhaps a flaky test?

**Comment by jamilbk** [comment]
@thomaseizinger Also we’re getting the failed vercel authorization I believe because you’re opening PRs from your personal branches. You should be able to push feature branches to the origin to open them directly in here to fix

**Comment by AndrewDryga** [comment]
@thomaseizinger thanks, fixed it in one of my branches.

**Pull request merged**
