### PR TITLE
feat(snownet): only keep the best possible candidate pair alive

### LINKED ISSUE #3789: snownet: reduce bandwidth usage of keep-alives
Currently, we keep all valid candidate pairs alive that we find during negotiation. There is a trade-off here where keeping them alive allows us to fallback to one of them very quickly if the current connection stops working. The downside is that we need to send keep-alives on those.

### PR DESCRIPTION
**Pull request by thomaseizinger**
This took me a while to figure out but I think the solution is quite neat. We are using ICE trickle which means there could be new candidates at any point in time. Thus, there really is never a good time to say "ICE is finished" and clean-up all other candidates (that is what non-trickle ICE would want you to do: https://datatracker.ietf.org/doc/html/rfc8445#section-8.3). But what we can do is, upon each nomination, look at our local candidates and invalidate all that are of the same priority or less.

For example, if we start with a connection via a relay, discard all other relay candidates but keep the host and server-reflexive ones. If the ICE agent then figures out a better path, it will give us a new nomination and we can discard even more candidates.

On the other hand, if hole-punching fails, str0m will eventually give up on certain candidate pairs because it is not receiving replies and consider them failed.

Thus, the behaviour that we are getting with this PR is: Try all possible candidate pairs but settle on the best possible one.

What is kind of neat is that, because we are still in ICE trickle mode, receiving a new candidate could still upgrade existing relayed connections to direct ones if the new candidate allows it.

The other side of this coin is that we won't have a fallback any more to other pairs if the current one fails. In that case, we will consider the entire connection failed, remove it and create a new one on the next connection intent.

Resolves: #3789.

### CODE REVIEW

**Comment by thomaseizinger** [comment]
I've tested this locally between a client and a gateway and it does successfully get rid of the relay candidate once we find a direct connection. At the moment, `str0m` still has a behaviour where it will form new pairs upon incoming binding requests. I am proposing to change this in https://github.com/algesten/str0m/pull/466.

With the linked patch applied (which I am doing in our fork of `str0m`), our clients will only send binding requests from the one remaining candidate:

```
2024-02-28T06:38:43.992088Z DEBUG str0m::ice_::agent: Send STUN request: [2404:e80:48e3:1:28c8:3912:460a:c830]:53323 -> [fd00::242:ac11:2]:40235 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "FbGE:lcVQ", priority: 1862270975, ice_controlling: 7323953937921134235 }, integrity_len: 0 }
2024-02-28T06:38:44.040654Z DEBUG str0m::ice_::agent: Send STUN request: [2404:e80:48e3:1:28c8:3912:460a:c830]:53323 -> [2600:1900:40f0:e339:0:e::]:50289 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "FbGE:lcVQ", priority: 1862270975, ice_controlling: 7323953937921134235 }, integrity_len: 0 }
2024-02-28T06:38:44.090831Z DEBUG str0m::ice_::agent: Send STUN request: [2404:e80:48e3:1:28c8:3912:460a:c830]:53323 -> [2600:1900:4120:f732:0:d::]:51733 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "FbGE:lcVQ", priority: 1862270975, ice_controlling: 7323953937921134235 }, integrity_len: 0 }
2024-02-28T06:38:44.140896Z DEBUG str0m::ice_::agent: Send STUN request: [2404:e80:48e3:1:28c8:3912:460a:c830]:53323 -> [2600:1900:4000:102d:0:d::]:49287 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "FbGE:lcVQ", priority: 1862270975, ice_controlling: 7323953937921134235 }, integrity_len: 0 }
2024-02-28T06:38:44.191145Z DEBUG str0m::ice_::agent: Send STUN request: [2404:e80:48e3:1:28c8:3912:460a:c830]:53323 -> [2600:1900:4020:eb:0:d::]:64397 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "FbGE:lcVQ", priority: 1862270975, ice_controlling: 7323953937921134235 }, integrity_len: 0 }
2024-02-28T06:38:44.240744Z DEBUG str0m::ice_::agent: Send STUN request: [2404:e80:48e3:1:28c8:3912:460a:c830]:53323 -> [2600:1900:40b0:1504:0:d::]:56369 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "FbGE:lcVQ", priority: 1862270975, ice_controlling: 7323953937921134235 }, integrity_len: 0 }
2024-02-28T06:38:44.291986Z DEBUG str0m::ice_::agent: Send STUN request: [2404:e80:48e3:1:28c8:3912:460a:c830]:53323 -> [2600:1900:4000:102d:0:d::]:63247 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "FbGE:lcVQ", priority: 1862270975, ice_controlling: 7323953937921134235 }, integrity_len: 0 }
2024-02-28T06:38:44.341160Z DEBUG str0m::ice_::agent: Send STUN request: [2404:e80:48e3:1:28c8:3912:460a:c830]:53323 -> [2600:1900:4120:f732:0:d::]:58034 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "FbGE:lcVQ", priority: 1862270975, ice_controlling: 7323953937921134235 }, integrity_len: 0 }
2024-02-28T06:38:44.391751Z DEBUG str0m::ice_::agent: Send STUN request: [2404:e80:48e3:1:28c8:3912:460a:c830]:53323 -> [2600:1900:4020:eb:0:d::]:63311 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "FbGE:lcVQ", priority: 1862270975, ice_controlling: 7323953937921134235 }, integrity_len: 0 }
2024-02-28T06:38:44.441507Z DEBUG str0m::ice_::agent: Send STUN request: [2404:e80:48e3:1:28c8:3912:460a:c830]:53323 -> [2600:1900:40b0:1504:0:d::]:60409 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "FbGE:lcVQ", priority: 1862270975, ice_controlling: 7323953937921134235 }, integrity_len: 0 }
2024-02-28T06:38:44.491600Z DEBUG str0m::ice_::agent: Send STUN request: [2404:e80:48e3:1:28c8:3912:460a:c830]:53323 -> [2600:1900:40f0:e339:0:e::]:58958 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "FbGE:lcVQ", priority: 1862270975, ice_controlling: 7323953937921134235 }, integrity_len: 0 }
```

That is still more than one because binding requests are sent for candidate _pairs_. As soon as this PR is deployed to staging, the same fix will land on the gateways which means they'll also invalidate all other candidates apart from the nominated one and stop responding to those binding requests which in turn will make us stop sending them because we consider them failed.

This can be verified locally with the docker-compose setup where only a single binding request is sent with these patches.

**Review by jamilbk — COMMENTED** [review]
Does this require an update on the Gateway as well? I just tested this and I'm not sure it's working as intended. Still getting these 20 or so STUN messages every ~second, minutes after the last ping stopped to the resource:

```
connlib	08:08:17.797432-0800	Send STUN request: 34.23.180.222:57832 -> 3.239.122.252:49673 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "JxPy:Eu1U", priority: 1849686271, ice_controlling: 3923758875851485240 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
connlib	08:08:17.801556-0800	Send STUN reply: [2600:1900:4020:eb:0:d::]:54568 -> [2600:1f18:2406:c402:77a0:5fc7:ec9:84e7]:40235 StunMessage { method: Binding, class: Success, attrs: Attributes { xor_mapped_address: [2600:1f18:2406:c402:77a0:5fc7:ec9:84e7]:40235 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
connlib	08:08:17.847389-0800	Send STUN request: 34.23.180.222:54568 -> 34.23.180.222:63311 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "JxPy:Eu1U", priority: 1849686783, ice_controlling: 3923758875851485240 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
connlib	08:08:17.847999-0800	Send STUN reply: 35.236.54.219:55313 -> 3.239.122.252:49673 StunMessage { method: Binding, class: Success, attrs: Attributes { xor_mapped_address: 3.239.122.252:49673 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
connlib	08:08:17.897936-0800	Send STUN reply: 35.236.54.219:53966 -> 3.239.122.252:49673 StunMessage { method: Binding, class: Success, attrs: Attributes { xor_mapped_address: 3.239.122.252:49673 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
connlib	08:08:17.947364-0800	Send STUN request: [2600:1900:4120:f732:0:d::]:55313 -> [2600:1900:4120:f732:0:d::]:58034 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "JxPy:Eu1U", priority: 1849688063, ice_controlling: 3923758875851485240 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
connlib	08:08:17.949891-0800	Send STUN reply: 34.23.180.222:54568 -> 3.239.122.252:49673 StunMessage { method: Binding, class: Success, attrs: Attributes { xor_mapped_address: 3.239.122.252:49673 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
connlib	08:08:18.003655-0800	Send STUN reply: [2600:1900:4020:eb:0:d::]:54568 -> [2600:1900:4020:eb:0:d::]:63311 StunMessage { method: Binding, class: Success, attrs: Attributes { xor_mapped_address: [2600:1900:4020:eb:0:d::]:63311 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
connlib	08:08:18.047566-0800	Send STUN request: 35.236.54.219:55313 -> 35.236.54.219:58034 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "JxPy:Eu1U", priority: 1849687807, ice_controlling: 3923758875851485240 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
connlib	08:08:18.052906-0800	Send STUN reply: 34.23.180.222:54568 -> 34.23.180.222:63311 StunMessage { method: Binding, class: Success, attrs: Attributes { xor_mapped_address: 34.23.180.222:63311 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
connlib	08:08:18.100156-0800	Send STUN reply: [2600:1900:4120:f732:0:d::]:55313 -> [2600:1900:4120:f732:0:d::]:58034 StunMessage { method: Binding, class: Success, attrs: Attributes { xor_mapped_address: [2600:1900:4120:f732:0:d::]:58034 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
connlib	08:08:18.150239-0800	Send STUN reply: 35.236.54.219:55313 -> 35.236.54.219:58034 StunMessage { method: Binding, class: Success, attrs: Attributes { xor_mapped_address: 35.236.54.219:58034 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
connlib	08:08:18.196774-0800	Send STUN request: [2600:1700:3ecb:2410:5021:c3f:4006:d09a]:60180 -> [2600:1f18:2406:c402:77a0:5fc7:ec9:84e7]:40235 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "JxPy:Eu1U", priority: 1862270975, use_candidate: true, ice_controlling: 3923758875851485240 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
connlib	08:08:18.447668-0800	Send STUN request: 192.168.1.65:49740 -> 3.239.122.252:49673 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "JxPy:Eu1U", priority: 1862270719, ice_controlling: 3923758875851485240 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
connlib	08:08:18.497211-0800	Send STUN request: [2600:1900:4120:f732:0:d::]:55313 -> [2600:1f18:2406:c402:77a0:5fc7:ec9:84e7]:40235 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "JxPy:Eu1U", priority: 1849688063, ice_controlling: 3923758875851485240 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
connlib	08:08:18.547399-0800	Send STUN request: [2600:1900:4120:f732:0:d::]:53966 -> [2600:1f18:2406:c402:77a0:5fc7:ec9:84e7]:40235 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "JxPy:Eu1U", priority: 1849687551, ice_controlling: 3923758875851485240 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
connlib	08:08:18.597289-0800	Send STUN request: [2600:1900:4020:eb:0:d::]:54568 -> [2600:1f18:2406:c402:77a0:5fc7:ec9:84e7]:40235 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "JxPy:Eu1U", priority: 1849687039, ice_controlling: 3923758875851485240 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
connlib	08:08:18.706959-0800	Send STUN reply: [2600:1900:4020:eb:0:d::]:57832 -> [2600:1f18:2406:c402:77a0:5fc7:ec9:84e7]:40235 StunMessage { method: Binding, class: Success, attrs: Attributes { xor_mapped_address: [2600:1f18:2406:c402:77a0:5fc7:ec9:84e7]:40235 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
connlib	08:08:18.748009-0800	Send STUN request: 35.236.54.219:55313 -> 3.239.122.252:49673 StunMessage { method: Binding, class: Request, attrs: Attributes { username: "JxPy:Eu1U", priority: 1849687807, ice_controlling: 3923758875851485240 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
connlib	08:08:18.759452-0800	Send STUN reply: 34.23.180.222:57832 -> 3.239.122.252:49673 StunMessage { method: Binding, class: Success, attrs: Attributes { xor_mapped_address: 3.239.122.252:49673 }, integrity_len: 0 }	FirezoneNetworkExtensionmacOS	dev.firezone.firezone
```

EDIT: Just read your followup comment. Need more coffee.

~~Let's merge this after the release today, when we can test it fully.~~

Since this doesn't appear to be worse than the current thing, I'll go ahead and approve/merge so we can ship it today with new gateways.

**Review by jamilbk — APPROVED** [review]

**Comment by AndrewDryga** [comment]
@thomaseizinger 

> The other side of this coin is that we won't have a fallback any more to other pairs if the current one fails. In that case, we will consider the entire connection failed, remove it and create a new one on the next connection intent.

WDYT about instead of removing them moving them to some fallback candidates list so we can try them if connection fails without doing a full reset?

**Comment by jamilbk** [comment]
Yeah I think @thomaseizinger is suggesting that for str0m here: https://github.com/algesten/str0m/issues/464

We would need to send a keepalive at maximum every 25 seconds to keep NATs open for the other candidates, so I guess the question is, what scenarios would cause a current direct/host connection to fail but a relay one succeed? The only thing I can think of is if the NAT topology changes (or NAT session otherwise gets clobbered) while we have an active connection. That seems rare, so we could just timeout the connection and create a new one.

The other possibilities for interrupted connections will be mostly the client changing network state (preventing all candidates from working) or the gateway rebooting (preventing all connections)

**Pull request merged**
