### PR TITLE
refactor(connlib): replace `webrtc` library with `str0m` and SANS-IO approach

### PR DESCRIPTION
**Pull request by thomaseizinger**
As part of replacing the `webrtc` library, we will need to write our own STUN/TURN client. This PR is a first step in that direction. It successfully replaces the `client` example of the relay with our own implementation.

```[tasklist]
- [ ] Upstream API exports to `str0m`
- [ ] Deal with openssl dependency in `str0m`
- [ ] Implement channels
```

### CODE REVIEW

**Comment by thomaseizinger** [comment]
@conectado I pushed some more stuff and added a few TODOs. It is not functional yet because I am still working out how to best compose everything. Feel free to have a look though and let me know what you think of it :)

**Comment by jamilbk** [comment]
@thomaseizinger We chatted last week during standup about maybe landing fundamental changes like this into a staging branch of some sort so that we can do a wholesale switchover in a single release. What's your appetite for that?

I realize it's not ideal, but things are Working™ with webrtc at the moment and it will help to keep major changes to the connectivity layer to a minimum as we work to release beta.

If this isn't a breaking change then nevermind the above comment

**Comment by jamilbk** [comment]
Aside from fixing the issue in #2661, I don't foresee too many more connlib changes in the pipeline that will make rebases a pain for you (hopefully)

**Comment by thomaseizinger** [comment]
> If this isn't a breaking change then nevermind the above comment

We should be able to ship it as a non-breaking change in regards to the network layer. I did adjust some things around how we exchange candidates with the portal but that can be reverted.

> @thomaseizinger We chatted last week during standup about maybe landing fundamental changes like this into a staging branch of some sort so that we can do a wholesale switchover in a single release. What's your appetite for that?

I think it makes most sense to just keep it in this PR to be honest. The commit history is clean at the moment, meaning apart from the last WIP commit, everything compiles and works at each commit.

Happy to keep this open until the beta is out, depending on the appetite for changes, we can merge individual commits from the front of the PR first :)
For example, we should probably land the fix in the relay where we currently don't allow reuse of channel numbers by different peers.

> Aside from fixing the issue in #2661, I don't foresee too many more connlib changes in the pipeline that will make rebases a pain for you (hopefully)

That would be great because I can already see that the actual transition away from `webrtc-rs` is going to be fairly invasive from a code change PoV.

**Comment by thomaseizinger** [comment]
Closing this in favor of the iterative approach outlined in https://github.com/firezone/firezone/issues/2966.

**Pull request closed without merging**
