### PR TITLE
feat(website): add product download links to footer

### PR DESCRIPTION
**Pull request by jamilbk**
Profeshunnal

### CODE REVIEW

**Comment by jamilbk** [comment]
Screenshot 2024-02-29 at 1 20 14 PM

**Review by ReactorScram — APPROVED** [review]

**Review by bmanifold — APPROVED** [review]
LGTM.  Think we should add these icons to the docs page as well?
https://www.firezone.dev/kb/user-guides

**Comment by jamilbk** [comment]
@bmanifold good call, added 
Screenshot 2024-02-29 at 3 44 04 PM

**Comment by bmanifold** [comment]
Nice!  I like the icons on the docs page, very slick.

**Pull request merged**
