### PR TITLE
Rename Devices to Clients in Elixir app

### PR DESCRIPTION
**Pull request by AndrewDryga**
Renaming it back to clients to reflect service accounts and headless clients use cases in the terminology. Such a rename will be very painful on live data so better if we do it early on.

### CODE REVIEW

**Review by jamilbk — APPROVED** [review]
LGTM. I can work on the connlib side of this to get tests passing again.

**Comment by jamilbk** [comment]
@AndrewDryga Or perhaps we should go ahead and do it in this PR?

**Comment by AndrewDryga** [comment]
@jamilbk I think it's better to do it in the same PR so we merge without breaking main branch.

**Comment by jamilbk** [comment]
K, pushing commits to change the connlib side now.

**Pull request merged**
