### PR TITLE
feat(blog): (draft) Desktop integration

### PR DESCRIPTION
**Pull request by ReactorScram**
Ideas for a blog I could write.

### CODE REVIEW

**Review by jamilbk — COMMENTED** [review]
This is a good start! There's a lot here, possibly covering multiple articles. I think the first one to try to write could be something like "Lessons learned using Tauri for a cross-platform security app".

The DNS article could be a separate one that goes in-depth about DNS headaches on different platforms and include Apple and Android battle stories.

If we have a third one, maybe it could be about FFI design patterns and testing.


Like an Engineering Diaries theme (maybe we could mention our `journal-` Slack convention too and how that's helped / not helped coms)

**Comment by ReactorScram** [comment]
👍 I'll start outlining / drafting one for just Tauri and open another PR for that

**Comment by ReactorScram** [comment]
Refs #5199

**Comment by ReactorScram** [comment]
Closing as unplanned

**Pull request closed without merging**
