### PR TITLE
refactor(connlib): simplify resource ordering by implementing Ord trait

### PR DESCRIPTION
**Pull request by conectado**
This is a small refactor that could be extracted from the work I'm doing for #2022

### CODE REVIEW

**Review by ReactorScram — APPROVED** [review]
LGTM

**Comment by thomaseizinger** [comment]
@conectado perf test is red 😭

**Comment by jamilbk** [comment]
> perf test is red

Will be in main momentarily

**Comment by jamilbk** [comment]
Updating to fix CI

**Pull request merged**
