### PR TITLE
feat(snownet): invalidate candidates

### PR DESCRIPTION
**Pull request by thomaseizinger**
Invalidating candidates should give `str0m` a hint that it may have to switch to a different candidate pair.

### CODE REVIEW

**Comment by thomaseizinger** [comment]
@conectado I am not sure what the best way to test this is other than merging it and experimenting with it on the integration branch!

**Comment by conectado** [comment]
> @conectado I am not sure what the best way to test this is other than merging it and experimenting with it on the integration branch!

let's just push this to the integration branch and test it there

**Comment by thomaseizinger** [comment]
> > @conectado I am not sure what the best way to test this is other than merging it and experimenting with it on the integration branch!
> 
> let's just push this to the integration branch and test it there

Sounds good! It is based on another PR so we need to merge both :)

**Comment by thomaseizinger** [comment]
> > @conectado I am not sure what the best way to test this is other than merging it and experimenting with it on the integration branch!
> 
> let's just push this to the integration branch and test it there

Merging this as per the above comment.

**Review by conectado — APPROVED** [review]

**Pull request merged**
