### PR TITLE
Fix release drafter compilation of erlang

### PR DESCRIPTION
**Pull request by jamilbk**
Fix erlang build errors occurring after version bump.

### CODE REVIEW

**Comment by princemaple** [comment]
Does a separate workflow overwrite the artifacts?

**Comment by jamilbk** [comment]
> Does a separate workflow overwrite the artifacts?

Hmm, not sure -- I had moved it to this workflow so we could pipe the outputs into the `softprops/action-gh-release` step. AFAIK I don't think you can pipe outputs or `depends_on` across workflows? Would be nice if we could.

**Comment by princemaple** [comment]
Nah was just thinking that the `workflow_dispatch` should be on that separate workflow because we don't need to rerun the whole build for the release notes update. Little bit duplication but if it doesn't overwrite the artifacts, it'd be quite handy. I can test it on a fork if you like.

**Comment by jamilbk** [comment]
> Nah was just thinking that the `workflow_dispatch` should be on that separate workflow because we don't need to rerun the whole build for the release notes update. Little bit duplication but if it doesn't overwrite the artifacts, it'd be quite handy. I can test it on a fork if you like.

Ah I see. Cool, sounds good.

**Pull request merged**
