### PR TITLE
Fixes for local development

### PR DESCRIPTION
**Pull request by jamilbk**
@mdp Seems I can't rebase your branch to resolve the conflict in your PR, so I made a couple small fixes and pushed up here to merge into the latest master. Feel free to rebase your branch if you want your PR merged, or just approve this to get your changes into master.

It's essentially your branch with the `wg_path`, `allow_unprivileged_device_management`, and `cookie_signing_salt` keys added to the `fz_http` config list. 

Refs #558

### CODE REVIEW

**Review by mdp — APPROVED** [review]
👍 Look good, thanks

**Comment by princemaple** [comment]
Hi @mdp, just wondering how this works. Does Codespace do some magic to expose the ports? The compose file doesn't expose any ports and is not running the phoenix app. How can I reach the app?

I'm mainly on Sublime and haven't played much with devcontainers. Apologies if it's a noob question.

**Comment by mdp** [comment]
Yeah, this is for use in a devcontainer setup like VSCode remote or
Codespaces, but it makes more sense that it should start the development
server when using vanilla compose. With regards to ports, they are
automatically forwarded with VSCode via ssh, or an nginx proxy on
Codespaces.

**Comment by princemaple** [comment]
Thanks for the reply!

**Pull request merged**
