### PR TITLE
chore(connlib): make device buffers smaller

### PR DESCRIPTION
**Pull request by conectado**
Since we expect a fixed MTU size, we can encode this in the size of the buffers for the device, we will never read or write more than the 1280 MTU we expect.

Note that the `write_buf` needs an extra 16 bytes for the aead tag that boringtun will copy over.

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]

**Comment by thomaseizinger** [comment]
Concept ACK but CI seems to disagree with your assumption :)

**Comment by conectado** [comment]
> Concept ACK but CI seems to disagree with your assumption :)

Ah! It seems like boringtun copies over the aead tag before decapsulating, fixing the size to take that into consideraiton

**Comment by thomaseizinger** [comment]
@conectado It keeps failing :(

**Comment by conectado** [comment]
> @conectado It keeps failing :(

I thought rebasing might've fixed it but no :cry:

**Comment by conectado** [comment]
8th time is the charm? lol

**Comment by thomaseizinger** [comment]
image

**Pull request merged**
