### PR TITLE
chore(connlib): implement some missing ICMP conversions

### PR DESCRIPTION
**Pull request by thomaseizinger**
So far, our packet translation only implemented the bare-minimum for ICMP to work. There are a few things left that haven't been dealt with. This PR adds additional conversions where it was easy.

There are still some left that require more elaborate mangling of the packet, like updating pointer fields.

### CODE REVIEW

**Review by ReactorScram — APPROVED** [review]
So this code converts from ICMPv6 to ICMPv4? I didn't realize that was both possible and so much effort

**Comment by thomaseizinger** [comment]
> So this code converts from ICMPv6 to ICMPv4? I didn't realize that was both possible and so much effort

Yes. It is actually reasonably well defined in https://datatracker.ietf.org/doc/html/rfc6145.

**Comment by conectado** [comment]
Part of why I didn't implement these conversions is that we use the `identity` field in the echo reply/request for our NAT which is not necessarily present in other ICMP types.

So, all of these will never be used since we don't support even natting those packets, which is the only point where we use the version conversion.

**Comment by thomaseizinger** [comment]
> Part of why I didn't implement these conversions is that we use the `identity` field in the echo reply/request for our NAT which is not necessarily present in other ICMP types.
> 
> So, all of these will never be used since we don't support even natting those packets, which is the only point where we use the version conversion.

Right, I didn't think of that. Don't you think this will be a problem? How do other NAT64 gateways handle this?

**Comment by thomaseizinger** [comment]
> > Part of why I didn't implement these conversions is that we use the `identity` field in the echo reply/request for our NAT which is not necessarily present in other ICMP types.
> > So, all of these will never be used since we don't support even natting those packets, which is the only point where we use the version conversion.
> 
> Right, I didn't think of that. Don't you think this will be a problem? How do other NAT64 gateways handle this?

I found this: https://superuser.com/a/135098

**Comment by conectado** [comment]
> > > Part of why I didn't implement these conversions is that we use the `identity` field in the echo reply/request for our NAT which is not necessarily present in other ICMP types.
> > > So, all of these will never be used since we don't support even natting those packets, which is the only point where we use the version conversion.
> > 
> > 
> > Right, I didn't think of that. Don't you think this will be a problem? How do other NAT64 gateways handle this?
> 
> I found this: https://superuser.com/a/135098

Yeah, I think this is what we should use the copy of the ICMP packet within the header. Which we also need to handle conversions for

I think for a first release we don't need it. Though I'd be happy to merge this since can construct that over this.

**Comment by conectado** [comment]
Manipulating the inner data of icmp will be a bit hairy, we need to particularly handle each error message and since libpnet doesn't handle the payload other than giving us the bytes we need to modify the bits manually or something similar.

**Comment by thomaseizinger** [comment]
> I think for a first release we don't need it.

Fair!

I did find this the other day: http://icmpcheck.popcount.org/
So I wouldn't be surprised if we end up with some strange bugs just because we don't handle ICMP messages properly.

**Comment by thomaseizinger** [comment]
> Though I'd be happy to merge this since can construct that over this.

Cool! Will merge then :)

**Pull request merged**
