### PR TITLE
fix(api): fix generated openapi spec

### PR DESCRIPTION
**Pull request by bmanifold**
(External contribution)

Hi, first thanks to @bmanifold for his awesome work! I've not yet tested the API but here is a first PR fixing various small mistakes in the generated openapi spec:

Schema names cannot contain spaces
Add missing path parameters in the spec
Remove duplicated endpoint for creating an identity (not sure about that, I'll let you check)
If you want to validate the generated spec you can paste it here: https://editor.swagger.io/ (or at the bottow of your swagger ui)

Please review commit by commit

### CODE REVIEW

**Review by jamilbk — APPROVED** [review]
LGTM. Thanks @Intuinewin

**Comment by jamilbk** [comment]
@Intuinewin Our branch protection rules require all commits to be signed. Would you be able to open a new PR against `contrib` with your commits signed? Much appreciated!

**Comment by Intuinewin** [comment]
@jamilbk My commits were signed, you can check on the original PR. It seems @bmanifold rebased them without signing them (or something else happened). I let you fix that, you still have my branch if you want to retry the merge on contrib

**Comment by bmanifold** [comment]
@Intuinewin Ah, yeah, I see what happened now.  When I merged to the `contrib` branch I did it in the Github UI and I selected rebase rather than squash, because I figured squashing would remove you from being credited, but thinking through it now, I realize there would be no way for it to sign those commits when rebasing in the UI.  Apologies for the confusion.

@jamilbk, what do you normally do for external contributions?  Do you do any merging in the Github UI or do you merge things locally to a `contrib` branch and then push that up and open a PR?

**Comment by jamilbk** [comment]
@bmanifold I think we want squash and merge instead. That won't preserve commits, but it does preserve the author. I've fixed this PR to do that -- should be good now.

**Comment by bmanifold** [comment]
@jamilbk, gotcha.  I thought for sure squash would remove the original author.  Sorry about that.

**Pull request merged**
