### PR TITLE
chore(ci): Use netstat instead of ss for release image tests

### LINKED ISSUE #4636: Flaky relay graceful shutdown test
https://github.com/firezone/firezone/actions/runs/8701133193/job/23862713655

### PR DESCRIPTION
**Pull request by jamilbk**
Fixes #4636

### CODE REVIEW

**Review by AndrewDryga — APPROVED** [review]

**Comment by thomaseizinger** [comment]
Just curious, why is netstat less flaky than ss?

**Comment by thomaseizinger** [comment]
AFAIK, ss is the more modern version?

**Comment by jamilbk** [comment]
My guess is because ss isn't in the base alpine image we use for releases / prod

**Comment by thomaseizinger** [comment]
> My guess is because ss isn't in the base alpine image we use for releases / prod

Lol, okay that is a problem. I didn't know they were constantly failing.

**Pull request merged**
