### PR TITLE
feat(windows): add `subzone` worker subprocess crate from abandoned IPC branch

### PR DESCRIPTION
**Pull request by ReactorScram**
I wasn't sure if we should try to preserve the Git history at all, so I just stuck it in a folder in the same repo.

This branch is identical to main but has the crate. The `subzone` branch has a version of the Windows client that builds on top of subzone.

### CODE REVIEW

**Review by jamilbk — COMMENTED** [review]
Nice work on polishing this up! Do you think this crate is useful on its own (outside Firezone)? If so we could stick in a new repository and probably give it a more descriptive name for publishing on crates.io (though I do like subzone).

If not, then we could merge it for use with the pre-firezone-connection Windows client in case we need to stick around on webrtc-rs for longer than expected (though I foresee this possibility to be low)

**Comment by ReactorScram** [comment]
It would be more useful on its own, I agree we probably won't need it. If we get stuck on `webrtc-rs` we can just use this crate as a dependency

**Review by thomaseizinger — APPROVED** [review]
Code LGTM!

The crate is currently neither tested in CI nor is it part of the workspace, meaning this code may bit-rot over time. At the same time, I don't really want to fix code that we don't actually use :)

My vote would go down for moving this into a separate repo that has a very basic Windows-only CI, i.e. fmt, clippy + test. That way we can evolve it if needed but we don't have to actively maintain it (dependency updates breaking stuff etc).

**Comment by thomaseizinger** [comment]
> If we get stuck on `webrtc-rs`

I'll do what is within my powers to avoid this!

**Comment by jamilbk** [comment]
> My vote would go down for moving this into a separate repo

Ah yeah, that sgtm. We can always choose to publish later on crates.io but not the other way around.  @ReactorScram made you admin on https://github.com/firezone/subzone so you should be able to stick it there.

**Comment by ReactorScram** [comment]
Okay I'll move the code there, link this PR for the Git history, and then close this

**Comment by ReactorScram** [comment]
It's up and I copied some of the clippy / fmt / test CI from the main Firezone repo https://github.com/firezone/subzone

**Pull request closed without merging**
