### PR TITLE
Display flash error when creating device results in interface error

### LINKED ISSUE #669: Crash Handling - Non-existing Wireguard Interface
If the Wireguard interface does not exist (eg. `firezone-ctl teardown-network` is ran) it will cause Phoenix to crash when retrieving device configurations:

```
2022-06-01_13:27:41.45204 21:27:41.431 [notice] Application fz_vpn exited: FzVpn.Application.start(:normal, []) returned an error: shutdown: failed to start child: FzVpn.Server
2022-06-01_13:27:41.45205     ** (EXIT) an exception was raised:
2022-06-01_13:27:41.45206         ** (RuntimeError)   Error executing command wg set wg-firezone peer Wj9hd2jyph30FW9Sg9DR+iv00GvJ2RQgaDrHkXsbLSk= allowed-ips 10.199.0.2/32,2001:db8::2/128 preshared-key /var/opt/firezone/cache/psks/12bea03727dde4aa09f46b9b05c2ba149a94e20c5bd8c82da8d46123cbc8f190.
2022-06-01_13:27:41.45206   Exit code: 1
2022-06-01_13:27:41.45206   Error message:
2022-06-01_13:27:41.45206   Unable to modify interface: No such device
2022-06-01_13:27:41.45206
2022-06-01_13:27:41.45206
2022-06-01_13:27:41.45207             (fz_common 0.3.16) lib/cli.ex:28: FzCommon.CLI.exec/2
2022-06-01_13:27:41.45207             (fz_vpn 0.3.16) lib/fz_vpn/server.ex:45: FzVpn.Server.apply_config_diff/2
2022-06-01_13:27:41.45207             (stdlib 3.17.2) gen_server.erl:423: :gen_server.init_it/2
2022-06-01_13:27:41.45207             (stdlib 3.17.2) gen_server.erl:390: :gen_server.init_it/6
2022-06-01_13:27:41.45207             (stdlib 3.17.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
2022-06-01_13:27:42.98854 {"Kernel pid terminated",application_controller,"{application_start_failure,fz_vpn,{{shutdown,{failed_to_start_child,'Elixir.FzVpn.Server',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<\"  Error executing command wg set wg-firezone peer Wj9hd2jyph30FW9Sg9DR+iv00GvJ2RQgaDrHkXsbLSk= allowed-ips 10.199.0.2/32,2001:db8::2/128 preshared-key /var/opt/firezone/cache/psks/12bea03727dde4aa09f46b9b05c2ba149a94e20c5bd8c82da8d46123cbc8f190.\n  Exit code: 1\n  Error message:\n  Unable to modify interface: No such device\n\n\">>},[{'Elixir.FzCommon.CLI',exec,2,[{file,\"lib/cli.ex\"},{line,28},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.FzVpn.Server',apply_config_diff,2,[{file,\"lib/fz_vpn/server.ex\"},{line,45}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,423}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,226}]}]}}},{'Elixir.FzVpn.Application',start,[normal,[]]}}}"}
2022-06-01_13:27:42.99470 Kernel pid terminated (application_controller) ({application_start_failure,fz_vpn,{{shutdown,{failed_to_start_child,'Elixir.FzVpn.Server',{#{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"  Error executing command wg set wg-firezone peer Wj9hd2jyph30FW9Sg9DR+iv00GvJ2RQgaDrHkXsbLSk= allowed-ips 10.199.0.2/32,2001:db8::2/128 preshared-key /var/opt/firezone/cache/psks/12bea03727dde4aa09f46b9b05c2ba149a94e20c5bd8c82da8d46123cbc8f190.\n  Exit code: 1\n  Error message:\n  Unable to modify interface: No such device\n\n">>},[{'Elixir.FzCommon.CLI',exec,2,[{file,"lib/cli.ex"},{line,28},{error_info,#{module => 'Elixir.Exception'}}]},{'Elixir.FzVpn.Server',apply_config_diff,2,[{file,"lib/fz_vpn/server.ex"},{line,45}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,423}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,390}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,226}]}]}}},{'Elixir.FzVpn.Application',start,[normal,[]]}}})
2022-06-01_13:27:42.99471
2022-06-01_13:27:42.99471 Crash dump is being written to: erl_crash.dump...done
```

NGINX will then return 502 errors since Phoenix crashed.

This case should be handled a bit more gracefully.

### PR DESCRIPTION
**Pull request by jamilbk**
Fixes #669

### CODE REVIEW

**Comment by akrousset** [comment]
This looks good! 

I have one outstanding question: Should we also add this around the remove_peer `fz_vpn` server call as well as part of this PR?

**Review by akrousset — COMMENTED** [review]
This looks good!

I have one outstanding question: Should we also add this around the remove_peer fz_vpn server call as well as part of this PR?

**Comment by jamilbk** [comment]
> This looks good!
> 
> I have one outstanding question: Should we also add this around the remove_peer fz_vpn server call as well as part of this PR?

Yeah, let me add that.

**Review by akrousset — COMMENTED** [review]
I believe we'd need to handle the error case here as well:

https://github.com/firezone/firezone/blob/c3205e8cdfb79748e1c99dacc0bfa43d14838a3e/apps/fz_vpn/lib/fz_vpn/server.ex#L27

**Review by akrousset — APPROVED** [review]
LGTM! 👍

**Pull request merged**
