### PR TITLE
test: refactor browser-based test to use deno

### PR DESCRIPTION
**Pull request by thomaseizinger**

### CODE REVIEW

**Comment by jamilbk** [comment]
Why deno? We already require a nodejs stack on the website and portal, so this adds another runtime to the repo.

**Comment by thomaseizinger** [comment]
> Why deno? We already require a nodejs stack on the website and portal, so this adds another runtime to the repo.

I figured it makes the testing infra easier? Whatever the website uses isn't actually shared with the tests so we don't really benefit from that being the same.

**Comment by jamilbk** [comment]
Yeah I would be open to it in the future if we could switch everything to it, but from a repo maintenance, supply chain, and ops overhead I feel the tradeoff isn't worth it at this point in time.

**Comment by thomaseizinger** [comment]
> Yeah I would be open to it in the future if we could switch everything to it, but from a repo maintenance, supply chain, and ops overhead I feel the tradeoff isn't worth it at this point in time.

Okay.

**Pull request closed without merging**
