### PR TITLE
test(android): Only run tests for x86_64 android

### PR DESCRIPTION
**Pull request by jamilbk**
Prevents compiling for all targets only to run tests on `x86`.

### CODE REVIEW

**Review by jasonboukheir — APPROVED** [review]
LGTM!

**Comment by jamilbk** [comment]
@jasonboukheir Do you know why the api-26 test is hanging? 

```
ERROR   | stop: Not implemented
```

**Comment by jasonboukheir** [comment]
> @jasonboukheir Do you know why the api-26 test is hanging?
> 
> ```
> ERROR   | stop: Not implemented
> ```

The api-29 test has the same output. I'm not sure

**Comment by jasonboukheir** [comment]
See https://github.com/ReactiveCircus/android-emulator-runner/issues/385

**Pull request merged**
