### PR TITLE
Add cookie encryption salt to session

### PR DESCRIPTION
**Pull request by conectado**
Closes firezone/product#365

### CODE REVIEW

**Review by jamilbk — APPROVED** [review]
Lgtm

**Comment by jamilbk** [comment]
@conectado Just double-checking -- did you happen to test local sessions still work fine after enabling this setting? I.e. sign in / sign out. I imagine a user would need to clear cookies once this is rolled out?

**Comment by conectado** [comment]
> @conectado Just double-checking -- did you happen to test local sessions still work fine after enabling this setting? I.e. sign in / sign out. I imagine a user would need to clear cookies once this is rolled out?

I have tested logging in and out and  that session is working. But haven't tested what happens after to a pre-existing session when the setting gets enabled. I'll do that now.

**Comment by conectado** [comment]
@jamilbk seems like after enabling the setting, the old unencrypted cookie gets invalidated and the user is prompted to login again. I think this is the desired behavior. And just in case I tested the other way around, disabling the feature, and it works the same way.

**Comment by jamilbk** [comment]
Awesome, thanks!

**Pull request merged**
