### PR TITLE
feat(phoenix-channel): support the `wire` log target

### PR DESCRIPTION
**Pull request by thomaseizinger**
Extracted out of: #3682.

### CODE REVIEW

**Review by ReactorScram — APPROVED** [review]
LGTM.
I'm not familiar with phoenix-channel, these are JSON messages describing pubsub topics or rooms being joined and left? That's why they're Strings and `Text`, it's not binary for the data plane?

**Comment by thomaseizinger** [comment]
> LGTM. I'm not familiar with phoenix-channel, these are JSON messages describing pubsub topics or rooms being joined and left? That's why they're Strings and `Text`, it's not binary for the data plane?

Correct yes, these are all the messages that we exchange with the portal to learn about resources, exchange candidates etc.

**Comment by ReactorScram** [comment]
Ah so this must be inside of the WebSocket connection.

**Comment by thomaseizinger** [comment]
> Ah so this must be inside of the WebSocket connection.

Yes. Phoenix channel is the website connection :)

**Pull request merged**
