### PR TITLE
fix(portal): Fix flash width and hero logo on auth pages

### PR DESCRIPTION
**Pull request by jamilbk**
# Before

Screenshot 2024-08-29 at 8 54 21 AM
Screenshot 2024-08-29 at 9 00 38 AM

Screenshot 2024-08-29 at 9 03 26 AM

# After

Screenshot 2024-08-29 at 8 54 30 AM
Screenshot 2024-08-29 at 9 00 54 AM
Screenshot 2024-08-29 at 9 09 54 AM
Screenshot 2024-08-29 at 9 14 52 AM

### CODE REVIEW

**Review by Patticatti — DISMISSED** [review]
Imo the blue message should still extend almost the full length of the screen as it may be easy to miss for the user, esp when it's such an important msg

**Comment by jamilbk** [comment]
@Patticatti Flash width change reverted for that global flash element

**Comment by AndrewDryga** [comment]
@jamilbk It feels like super huge logo on sign in flow just adds a ton of distraction, it's as big as the form itself: 

image

**Comment by bmanifold** [comment]
> It feels like super huge logo on sign in flow just adds a ton of distraction, it's as big as the form itself

I can see what @AndrewDryga is saying here.  Would it make sense to split the difference?

**Comment by jamilbk** [comment]
> > It feels like super huge logo on sign in flow just adds a ton of distraction, it's as big as the form itself
> 
> 
> 
> I can see what @AndrewDryga is saying here.  Would it make sense to split the difference?

If we change it here, we need to change it on all auth views because they use the same layout.

Otherwise, the logo + hero text will jump sizes as you navigate between views.

**Comment by jamilbk** [comment]
> > > It feels like super huge logo on sign in flow just adds a ton of distraction, it's as big as the form itself
> > 
> > 
> > I can see what @AndrewDryga is saying here.  Would it make sense to split the difference?
> 
> If we change it here, we need to change it on all auth views because they use the same layout.
> 
> Otherwise, the logo + hero text will jump sizes as you navigate between views.

I've reduced it from h-32 to h-24.

**Review by bmanifold — APPROVED** [review]
LGTM

**Pull request merged**
