### PR TITLE
Don't set default url opts in runtime

### PR DESCRIPTION
**Pull request by jamilbk**
Allows for upstream config to take effect.

### CODE REVIEW

**Review by princemaple — COMMENTED** [review]
Does this change actually work? Before and after look logically equivalent to me. Do we want `check_origin: false`?

**Comment by jamilbk** [comment]
@princemaple This is mostly just refactoring -- I was debugging the WebSocket issues locally and realized that the `url.host` setting from the compile-time config files will never take effect if `EXTERNAL_URL` is not set.

**Comment by princemaple** [comment]
Ah cool. That's why it's equivalent before & after, besides the default :)

**Review by princemaple — APPROVED** [review]
👍

**Pull request merged**
