### PR TITLE
Speed up admin ui

### PR DESCRIPTION
**Pull request by princemaple**
Speed up navigation, especially in dev. Click around, go nuts.

If you use devcontainer, make sure you go to localhost, not localhost:4000

https://user-images.githubusercontent.com/1329716/169011618-bc62b44e-fb3c-44f2-9a62-a4c969b28fd0.mp4

### CODE REVIEW

**Review by jamilbk — CHANGES_REQUESTED** [review]
This is awesome, thanks for liveview-ing the whole admin portal!

I only found one issue: on the `Account` page the `Active Sessions` table fails to load when `live_redirected` to. If you refresh the page it loads fine. This is because the table is populated from a notification channel and JS helper here: https://github.com/firezone/firezone/blob/master/apps/fz_http/assets/js/live_view.js#L63

You can see I've been meaning to clean it up a bit... maybe its time for this little JS helper to get some love and perhaps graduate into its own LiveView?

**Comment by princemaple** [comment]
@jamilbk rebuilt it with liveview and now it has live update - duplicate the page, you will see a new session pop up.

https://user-images.githubusercontent.com/1329716/169162358-7245f411-ce29-4224-a499-f089bacb4cce.mp4

**Comment by princemaple** [comment]
Actually this probably isn't new 😅 presence.onSync did the same. Got too excited for a sec.

**Comment by jamilbk** [comment]
This looks fantastic.

**Review by jamilbk — APPROVED** [review]

**Pull request merged**
