### PR TITLE
feat(rust): Headless Windows client

### LINKED ISSUE #1768: 1.0 Beta Windows Client
High-level issue to track work / discussion on the Windows client. Issues arranged in dependency order and should aim to be tackled top-to-bottom.

# Userspace application

- [x] Boilerplate / CI/CD #2715
- [x] Encrypted storage #2740
- [x] Git check-in and attribution for wintun #2758 
- [x] Tray icon and menu #2712
- [x] Permissions #2751
- [x] Connlib callbacks / integration #2716
- [x] Auth #2711
- [x] Settings #2714
- [x] Wintun packaging and install #2758
- [x] SplitDNS #2713
- [x] Auto-update #2717
- [x] #3017

See https://github.com/firezone/product/blob/main/architecture/connlib-client-ffi.md for an overview on the functions needed at the userspace <-> tunnel boundary.

# Tunnel

@conectado has most of this done already

# Headless operation

(Split to #3782)

### PR DESCRIPTION
**Pull request by dvasanth**
- Successfully compiled the client on Windows Platform
- Used the wintun for adapter creation
- Used Iphlpapi for IPv4 address assignment after clearing previous address 
- Assigned the lowest interface & route metric value to prefer route through tun adapter 
- Able to ping & perform iperf3 operations on the network resources from Windows 11 
- TODO: Add IPv6 support, DNS request handling, Performance improvement 
Closes #1768

### CODE REVIEW

**Comment by jamilbk** [comment]
Thanks for the contribution! I've updated from latest `main` and approved the CI to run.

@firezone/engineering -- for context, this was a contribution by one of our users from our [Users Slack workspace](https://firezone-users.slack.com).

@dvasanth I'm not sure we even have any Windows machines set up at the moment (yet) to test this manually. In CI, we use `docker` for our integration tests so we may need another approach to test the headless Windows client.

**Comment by thomaseizinger** [comment]
> @dvasanth I'm not sure we even have any Windows machines set up at the moment (yet) to test this manually. In CI, we use `docker` for our integration tests so we may need another approach to test the headless Windows client.

Couldn't we build the headless client outside of docker on the target machine instead of within docker? Then we could make a matrix of running the headless client on linux, windows (and perhaps MacOS?) against docker-compose environment.

**Comment by jamilbk** [comment]
> > @dvasanth I'm not sure we even have any Windows machines set up at the moment (yet) to test this manually. In CI, we use `docker` for our integration tests so we may need another approach to test the headless Windows client.
> 
> Couldn't we build the headless client outside of docker on the target machine instead of within docker? Then we could make a matrix of running the headless client on linux, windows (and perhaps MacOS?) against docker-compose environment.

Yeah, that would be ideal. We could run [service containers](https://docs.github.com/en/actions/using-containerized-services/about-service-containers) to bring the app up, then run headless clients against those to test, assuming a matrix job can run against service containers?

**Comment by thomaseizinger** [comment]
> > > @dvasanth I'm not sure we even have any Windows machines set up at the moment (yet) to test this manually. In CI, we use `docker` for our integration tests so we may need another approach to test the headless Windows client.
> > 
> > 
> > Couldn't we build the headless client outside of docker on the target machine instead of within docker? Then we could make a matrix of running the headless client on linux, windows (and perhaps MacOS?) against docker-compose environment.
> 
> Yeah, that would be ideal. We could run [service containers](https://docs.github.com/en/actions/using-containerized-services/about-service-containers) to bring the app up, then run headless clients against those to test, assuming a matrix job can run against service containers?

Unfortunately, service containers only work on Linux unless I am misunderstanding the docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idservices

**Comment by jamilbk** [comment]
> Unfortunately, service containers only work on Linux unless I am misunderstanding the docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idservices

Yeah I think that's what I was thinking. By "bring the app up" I meant to say "bring the control plane up"

**Comment by conectado** [comment]
Thank @dvasanth I'll start working over these changes to resolve conflicts in the new branch [windows-headless-client](https://github.com/firezone/firezone/tree/windows-headless-client)

**Pull request merged**
