### PR TITLE
fix(connlib): exclude sentinel dns range for resources ips

### PR DESCRIPTION
**Pull request by conectado**
In the future we will want to refactor this to a builder pattern to prevent the number of parameters from growing and have them clearer but this works simply for now.

Found while discussing #4174

### CODE REVIEW

**Review by jamilbk — COMMENTED** [review]
LGTM, deferring to @thomaseizinger

**Review by thomaseizinger — APPROVED** [review]
If you are always passing constants, why don't you just make two constructors that use those constants internally?

Seems to be easier to understand to me.

Also, can `IpProvider` just move into `firezone_tunnel`? Why does it sit in shared?

**Comment by conectado** [comment]
To be honest I still prefer passing the ranges in the constructor, seems more explicit to me.

**Comment by thomaseizinger** [comment]
> To be honest I still prefer passing the ranges in the constructor, seems more explicit to me.

It is just a level of indirection though. Unless we use it with dynamic ranges, it seems to make more sense to just make two constructors:

```rust
impl IpProvider {
	fn client() -> Self { }
	fn gateway() -> Self { }
}
```

**Comment by thomaseizinger** [comment]
> > To be honest I still prefer passing the ranges in the constructor, seems more explicit to me.
> 
> It is just a level of indirection though. Unless we use it with dynamic ranges, it seems to make more sense to just make two constructors:

You can always dispatch to a more generic constructor from there.

**Comment by thomaseizinger** [comment]
> > To be honest I still prefer passing the ranges in the constructor, seems more explicit to me.
> 
> It is just a level of indirection though. Unless we use it with dynamic ranges, it seems to make more sense to just make two constructors:
> 
> ```rust
> impl IpProvider {
> 	fn client() -> Self { }
> 	fn gateway() -> Self { }
> }
> ```

Oh I misunderstand how this is used. Nvm the `client` / `gateway` terminology.

**Pull request merged**
