### PR TITLE
ci: Publish Gateway 1.4.0

### PR DESCRIPTION
**Pull request by jamilbk**
Publish the 1.4.0 release so it's available at `/api/releases` and will send upgrade Gateway notifications.

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]

**Comment by thomaseizinger** [comment]
If I wanted to make another release with https://github.com/firezone/firezone/pull/7188 and https://github.com/firezone/firezone/pull/7189, will that send two update notifications in a row? Or are you talking about the manual message tracked in #7112?

**Comment by jamilbk** [comment]
> If I wanted to make another release with #7188 and #7189, will that send two update notifications in a row? Or are you talking about the manual message tracked in #7112?

That's a good question. @bmanifold might know how that works in more detail, but I believe those notifications are gated so as not to spam anyone.

**Comment by thomaseizinger** [comment]
> > If I wanted to make another release with #7188 and #7189, will that send two update notifications in a row? Or are you talking about the manual message tracked in #7112?
> 
> That's a good question. @bmanifold might know how that works in more detail, but I believe those notifications are gated so as not to spam anyone.

Cool. It is not super critical to release right away after so we don't need to block this.

**Comment by bmanifold** [comment]
> That's a good question. @bmanifold might know how that works in more detail, but I believe those notifications are gated so as not to spam anyone.

Yeah, the outdated Gateway notifications are only sent once a week (and actually at the moment no one is likely getting sent a notification, because we decided to make it an opt-in feature and I don't think anyone has done that yet).  So, there is no real concern about people getting multiple notifications right now.

**Pull request merged**
