### PR TITLE
fix(windows): clear all routes when setting new IPs

### PR DESCRIPTION
**Pull request by thomaseizinger**
Related: #5392.

### CODE REVIEW

**Comment by thomaseizinger** [comment]
@conectado Putting this up here so we don't forget. We could maybe also remove all routes and re-add them? Not sure what exactly the patches were that you had locally.

**Comment by conectado** [comment]
For default route #6051 might be needed to do but I'll test if this PR is just enough and report back

**Comment by conectado** [comment]
> For default route #6051 might be needed to do but I'll test if this PR is just enough and report back

@thomaseizinger this is the patch that I had locally

**Comment by thomaseizinger** [comment]
Superseded by #6051.

**Pull request closed without merging**
