### PR TITLE
chore(gateway): remove domain response (breaks < 1.1.0 clients)

### PR DESCRIPTION
**Pull request by thomaseizinger**
Prior to version 1.1.0, clients did not have an embedded DNS resolver and relied on the gateway for DNS resolution. In that design, the gateway responded with the IPs that the domain resolved to.

Our next iteration of the control protocol (#6461) will decouple the details of how DNS works from the flow-authorization. As a result, we will need to be able to establish a flow for a DNS resource without knowing which concrete domain the client is going to access.

Without a concrete domain, we cannot send anything back to these old clients, meaning we unfortunately have to break compatibility with < 1.1.0 clients as part of implementing the new control protocol.

### CODE REVIEW

**Comment by jamilbk** [comment]
Does this break `1.1.x` clients? E.g. `1.1.5`?

Screenshot 2024-09-16 at 4 17 56 PM

**Comment by jamilbk** [comment]
> Does this break `1.1.x` clients? E.g. `1.1.5`?
> 
> Screenshot 2024-09-16 at 4 17 56 PM

Nevermind, I see now this breaks only `< 1.1.0` clients.

**Review by conectado — APPROVED** [review]
Changes look good if we think we can break backwards compatibility now

**Comment by jamilbk** [comment]
I think we should be ok!

Screenshot 2024-09-17 at 4 44 25 PM

**Review by jamilbk — APPROVED** [review]

**Pull request merged**
