### PR TITLE
ci(windows): add SHA256 hashes for artifacts

### LINKED ISSUE #2997: windows: SHA256 for build artifacts
If nothing else: https://stackoverflow.com/questions/63396620/how-can-i-compare-a-files-sha256-hash-in-powershell-to-a-known-value#63396621

### PR DESCRIPTION
**Pull request by ReactorScram**
Fulfills #2997 

cd.yml changes are always blind so it may break the draft release when it goes into main. Just let me know.

I should probably just switch it to Bash so it's easier to test.

### CODE REVIEW

**Comment by ReactorScram** [comment]
The changes in `_rust.yml` work at least: 
image

**Review by jamilbk — APPROVED** [review]
LGTM. The `msi` is the installer package, while the `exe` can be run standalone?

**Comment by ReactorScram** [comment]
> LGTM. The `msi` is the installer package, while the `exe` can be run standalone?

Correct. The exe might be nice for power users who want multiple versions installed side-by-side, but it's harder to support than the MSI, which will almost always install to the same C:/Program Files/Firezone Windows Client path, unless they pick a custom path or install to some other drive.

**Comment by jamilbk** [comment]
@ReactorScram In the docs I'll be sure to link to the MSI then.

**Comment by ReactorScram** [comment]
Good to go 
image

**Comment by jamilbk** [comment]
@ReactorScram Ah, sorry I totally missed this. I think there's a format for these sha256sum files we need to adhere to:

```
98fa59093124f62b434312fc133b70b846930d89cc72d38ba998ef33db6bb099  linux-client-arm
```

Which is:

```
<sha hash><space><space><filename corresponding to hash>
```

**Comment by jamilbk** [comment]
https://www.ibm.com/docs/en/zos/2.4.0?topic=descriptions-sha256-calculate-check-sha-256-cryptographic-hashes

Or maybe Windows has its own format? The above link is for the `sha256` tool on *nixes

**Comment by ReactorScram** [comment]
Yeah it's something strange the Powershell hash cmdlet does.
I guess it's meant for end users who download it to verify on their own systems? So I can check how to validate with Powershell.

If it has to match the Linux style, I can try using Bash instead of Powershell, the Github runners might have sha256sum in their Bash environments

**Comment by jamilbk** [comment]
> If it has to match the Linux style, I can try using Bash instead of Powershell, the Github runners might have sha256sum in their Bash environments

Naw, if that's what Powershell generates / expects then let's go with that.

**Comment by ReactorScram** [comment]
Actually I have no clue how to validate it, I'd just been eyeballing it.
Opened a ticket here https://github.com/firezone/firezone/issues/3221

**Pull request merged**
