### PR TITLE
Bump all deps and fix Phoenix to v1.7

### PR DESCRIPTION
**Pull request by AndrewDryga**

### CODE REVIEW

**Comment by jamilbk** [comment]
Looks like Dialyzer is complaining about the `Phoenix.Token.verify/4` call. At first glance I don't see anything wrong. Perhaps the PLT cache needs to be busted?

**Comment by AndrewDryga** [comment]
@jamilbk I think it's a Dialyzer issue: https://github.com/phoenixframework/phoenix/commit/2aa5c9b0d6d8a6edfb2df2375868928d02780a0a#r102624979

**Comment by AndrewDryga** [comment]
Pending https://github.com/phoenixframework/phoenix/issues/5321

**Review by jamilbk — APPROVED** [review]
I guess Dialyzer got fixed?

**Comment by AndrewDryga** [comment]
@jamilbk the type specs were fixed in Phoenix

**Pull request merged**
