### PR TITLE
connlib: error out with http 4xx instead of trying to reconnect

### LINKED ISSUE #2013: Immediately disconnect connlib when portal returns bad token errors
When a token is expired, connlib currently tries to reconnect for some time before disconnecting the client and returning it to a state where the user can sign in again.

Instead, when we receive the 401 from the portal we should disconnect immediately.

### PR DESCRIPTION
**Pull request by conectado**
fixes #2013 

Stops the reconnect loop on a 4xx error.

Right now it seems like android doesn't handle `on_disconnect` properly, just logging instead of going back to sign-in screen.

### CODE REVIEW

**Review by jamilbk — APPROVED** [review]
Well done!

**Comment by thomaseizinger** [comment]
Should the gateway also exit? Because this PR doesn't apply the same fix to the gateway now that https://github.com/firezone/firezone/pull/2244 is merged.

**Comment by conectado** [comment]
> Should the gateway also exit? Because this PR doesn't apply the same fix to the gateway now that https://github.com/firezone/firezone/pull/2244 is merged.

I was waiting for #2244 to be merged before introducing it into gateways, it's not so important though since there's nothing one can do on a gateway save for an admin to intervene, also gateway's tokens never expire.

**Comment by thomaseizinger** [comment]
I think it might be worth considering whether the gateway should reconnect at all by itself? At the moment, we kill the tunnel but re-initalise it with the same private key. I think that means the wireguard tunnel stays alive from the client's perspective if we reconnect to the portal fast enough, right?

We could simplify the code a fair bit if we would remove the reconnect loop and rely on our environment to restart us, e.g. systemd, kubernetes, etc. The relay does the same thing.

The main question is: Is there a meaningful case where _only _ the connection to the portal dies, we reconnect successfully and can thus keep wireguard tunnels to clients alive? If yes, should we look for an alternative solution to persisting that wireguard key?

**Comment by jamilbk** [comment]
> I think it might be worth considering whether the gateway should reconnect at all by itself? At the moment, we kill the tunnel but re-initalise it with the same private key. I think that means the wireguard tunnel stays alive from the client's perspective if we reconnect to the portal fast enough, right?
> 
> We could simplify the code a fair bit if we would remove the reconnect loop and rely on our environment to restart us, e.g. systemd, kubernetes, etc. The relay does the same thing.
> 
> The main question is: Is there a meaningful case where _only _ the connection to the portal dies, we reconnect successfully and can thus keep wireguard tunnels to clients alive? If yes, should we look for an alternative solution to persisting that wireguard key?

Yeah, for minor control plane hiccups (like if portal flaps for a minute or two) we want to maintain data plane flows I think, which means maintaining the keys.

But we only need to do this in memory right? A restart of the Gateway process would disrupt data plane anyway and so propagating new keys would be fine

**Comment by thomaseizinger** [comment]
Thinking about it, if we throw away the tunnel state, then all the ephemeral encryption keys are gone so the wireguard tunnel is broken anyway, isn't it?

At least that is how it is currently implemented. I have to check if that is what it did before too otherwise I may have accidentially broken that in my last refactoring :)

**Comment by conectado** [comment]
> Thinking about it, if we throw away the tunnel state, then all the ephemeral encryption keys are gone so the wireguard tunnel is broken anyway, isn't it?
> 
> At least that is how it is currently implemented. I have to check if that is what it did before too otherwise I may have accidentially broken that in my last refactoring :)

It used to be that the tunnel state was maintained separtedly from the portal channel. 

I missed that change in my review, we should revert that.

**Comment by thomaseizinger** [comment]
See https://github.com/firezone/firezone/pull/2278.

**Pull request merged**
