### PR TITLE
Use named volume for postgres

### PR DESCRIPTION
**Pull request by jamilbk**

### CODE REVIEW

**Comment by gchamon** [comment]
@jamilbk hey there!
Is there a specific issue that naming a volume solves? I am only asking because I modeled my backup process around having the entire postgres volume mounted in the same folder I would later sync to S3. Having a named volume makes the backup process somewhat harder and I would rather just keep mapping the volume to FZ_INSTALL_DIR, if this isn't a problem for me.

**Comment by jamilbk** [comment]
Yes, unfortunately. Using a local path as a volume creates [this issue](https://forums.docker.com/t/data-directory-var-lib-postgresql-data-has-wrong-ownership-on-linux/97057/7). Using a named volume is the simplest solution to fix the problem.

Happy to accept a PR for the template if you find a workaround. The `postgres` README on DockerHub has this to say about it:

---

# Arbitrary `--user` Notes

As of [docker-library/postgres#253](https://github.com/docker-library/postgres/pull/253), this image supports running as a (mostly) arbitrary user via `--user` on `docker run`.

The main caveat to note is that `postgres` doesn't care what UID it runs as (as long as the owner of `/var/lib/postgresql/data` matches), but `initdb` *does* care (and needs the user to exist in `/etc/passwd`):

```console
$ docker run -it --rm --user www-data -e POSTGRES_PASSWORD=mysecretpassword postgres
The files belonging to this database system will be owned by user "www-data".
...

$ docker run -it --rm --user 1000:1000 -e POSTGRES_PASSWORD=mysecretpassword postgres
initdb: could not look up effective user ID 1000: user does not exist
```

The three easiest ways to get around this:

1.	use the Debian variants (not the Alpine variants) and thus allow the image to use [the `nss_wrapper` library](https://cwrap.org/nss_wrapper.html) to "fake" `/etc/passwd` contents for you (see [docker-library/postgres#448](https://github.com/docker-library/postgres/pull/448) for more details)

2.	bind-mount `/etc/passwd` read-only from the host (if the UID you desire is a valid user on your host):

	```console
	$ docker run -it --rm --user "$(id -u):$(id -g)" -v /etc/passwd:/etc/passwd:ro -e POSTGRES_PASSWORD=mysecretpassword postgres
	The files belonging to this database system will be owned by user "jsmith".
	...
	```

3.	initialize the target directory separately from the final runtime (with a `chown` in between):

	```console
	$ docker volume create pgdata
	$ docker run -it --rm -v pgdata:/var/lib/postgresql/data -e POSTGRES_PASSWORD=mysecretpassword postgres
	The files belonging to this database system will be owned by user "postgres".
	...
	( once it's finished initializing successfully and is waiting for connections, stop it )
	$ docker run -it --rm -v pgdata:/var/lib/postgresql/data bash chown -R 1000:1000 /var/lib/postgresql/data
	$ docker run -it --rm --user 1000:1000 -v pgdata:/var/lib/postgresql/data postgres
	LOG:  database system was shut down at 2017-01-20 00:03:23 UTC
	LOG:  MultiXact member wraparound protections are now enabled
	LOG:  autovacuum launcher started
	LOG:  database system is ready to accept connections
	```

---

I went down the rabbit hole of trying those workarounds but couldn't get it to work reliably on Windows/Mac/Linux.

**Comment by gchamon** [comment]
Maybe the easiest and most production ready workaround for me that targets cloud deployment would be to use managed database offers instead of a local database. I only think that, although it frees the main vpn compute instance to do actual work, it may be overkill to use a separate managed database.

I haven't seen any issues with permissions though. I also migrated my installation from a temporary URL to a permanent one, requiring me to recreate the compute instance in which the VPN runs, and everything went smoothly, no permission issues.

So maybe I'm in the clear? Btw I use Amazon Linux 2 as a host OS.

I will keep an eye on the system and change to named volumes in case I see any issues.

Workaround for my backup process would be easy though. I would maybe have to sync the contents from the virtual volume to the installation folder, sync it to s3 and erase it. It would duplicate data and require potentially double the usual disk space, but for small-ish setups this shouldn't be a problem. I would expect cpu to be an issue way before disk in case of a postgres installation growing past a couple of GB in disk space.

**Comment by jamilbk** [comment]
Yeah, the perms issue only comes up when initializing a fresh DB. If you have an existing DB then I don’t think it’s as much of a problem.

Many firezone production deployments are using it with an external DB AFAIK. So that’s an option as well.

You could also modify your local docker-compose.yml template to use a local dir mount for the postgres data — simply copy the db files over and update the volume path and it should work fine.

The docker-compose file in `~/.firezone` is meant to be customized by the user.

**Comment by gchamon** [comment]
Thanks a lot! This was very helpful!

**Pull request merged**
