### PR TITLE
Revert to OTP 24

### PR DESCRIPTION
**Pull request by jamilbk**
Triaged the SSL timeout issue -- it was due to OTP 25.

Reverting to OTP 24 fixes a timeout with HTTPoison when connecting to certain SSL sites (e.g. Azure)

### CODE REVIEW

**Comment by princemaple** [comment]
Hmm 😢

In order to upgrade in the future, we will have to consider 1) update openid_connect to have a http client behaviour and enable custom http client implementation, or 2) switch to a different lib that already supports http client customization or uses finch.

**Comment by princemaple** [comment]
Need to bust the build cache for it to work again.

**Review by princemaple — DISMISSED** [review]

**Comment by jamilbk** [comment]
> Hmm 😢
> 
> In order to upgrade in the future, we will have to consider 1) update openid_connect to have a http client behaviour and enable custom http client implementation, or 2) switch to a different lib that already supports http client customization or uses finch.

Yeah I'm hoping someone will find the issue with httpoison and fix it, but if not we should be able to switch out the http client lib without too much hassle.

**Comment by princemaple** [comment]
openid_connect is actually not very well coded. It's basically locked into httpoison because of its pattern matching on response. So, despite having a configurable http client, it really only works with httpoison.

**Comment by jamilbk** [comment]
@princemaple Yeah, the lib does seem fairly poorly architected. Not saying we should do this now, but maybe in the future we could swap out `openid_connect` with [`oauth2`](https://github.com/ueberauth/oauth2#client-credentials-flow).

**Comment by jamilbk** [comment]
@princemaple I'm cleaning up the CI runners a bit -- @akrousset and I had installed llvm and clang to build rustler stuff but ended up extracting that into its own lib like you suggested. Just noting here in case you see building errors related to `ICU`

**Comment by princemaple** [comment]
Cool, thanks for the heads up.

**Pull request merged**
