### PR TITLE
fix(portal): Adopt LiveView 1.0 breaking changes

### LINKED ISSUE #5545: no function clause matching in Web.Policies.Components.day_of_week_index/1
https://console.cloud.google.com/monitoring/alerting/incidents/0.nehb3pggzn60?channelType=slack&project=firezone-staging

```
** (FunctionClauseError) no function clause matching in Web.Policies.Components.day_of_week_index/1
    (web 0.1.0+deadbeef) lib/web/live/policies/components.ex:217:in `Web.Policies.Components.day_of_week_index("_unused_F")'
    (elixir 1.17.1) lib/enum.ex:3348:in `anonymous fn/2 in Enum.sort_by/3'
    (elixir 1.17.1) lib/enum.ex:1711:in `anonymous fn/3 in Enum.map/2'
    (stdlib 6.0) maps.erl:860:in `:maps.fold_1/4'
    (elixir 1.17.1) lib/enum.ex:2543:in `Enum.map/2'
    (elixir 1.17.1) lib/enum.ex:3348:in `Enum.sort_by/3'
    (web 0.1.0+deadbeef) lib/web/live/policies/components.ex:57:in `anonymous fn/2 in Web.Policies.Components.map_condition_values/1'
    (elixir 1.17.1) lib/map.ex:676:in `Map.update/4'
```

### PR DESCRIPTION
**Pull request by AndrewDryga**
Closes https://github.com/firezone/firezone/issues/5545

### CODE REVIEW

**Review by jamilbk — COMMENTED** [review]
LGTM, will let @bmanifold approve just for a second pair of eyes.

Thanks for the quick around!

**Comment by AndrewDryga** [comment]
Also changed the style of select inputs and radio buttons to make them look more unified:

Before
Screenshot 2024-06-25 at 12 48 20 PM

After
Screenshot 2024-06-25 at 12 48 24 PM

**Comment by jamilbk** [comment]
> Also changed the style of select inputs and radio buttons to make them look more unified:
> 
> Before Screenshot 2024-06-25 at 12 48 20 PM
> 
> After Screenshot 2024-06-25 at 12 48 24 PM

The design book is paying off!

**Review by bmanifold — APPROVED** [review]
LGTM

**Pull request merged**
