### PR TITLE
Add Swift build cache to CI

### PR DESCRIPTION
**Pull request by jamilbk**
- Cache build outputs as well as package manager resolved cache
- Write a new cache on `main` if anything in `swift/` or `rust/` changes, and match on successively broader `restore-keys`. Swift loves cached builds but its build cache is fairly large, so I thought this might be an improvement over simply writing the cache to `github.sha` in case anything outside of those directories changes.
- ~~Split macOS `x86_64` and `aarch64` builds with a matrix to parallelize them, will join them into the final bundle during the `cd` stage~~ Edit: We want to build these together in order to create a Universal Binary artifact more easily.

### CODE REVIEW

**Comment by thomaseizinger** [comment]
> * Cache build outputs as well as package manager resolved cache
> 
>     * Write a new cache on `main` if anything in `swift/` or `rust/` changes, and match on successively broader `restore-keys`. Swift loves cached builds but its build cache is fairly large, so I thought this might be an improvement over simply writing the cache to `github.sha` in case anything outside of those directories changes.
> 
>     * Split macOS `x86_64` and `aarch64` builds with a matrix to parallelize them, will join them into the final bundle during the `cd` stage

Great ideas! I was also considering a matrix but didn't know enough about the swift build-process to do it. Have you seen the errors regarding the cache keys?

image

**Comment by jamilbk** [comment]
@thomaseizinger I reverted back to build both archs on `macOS` and using just the `platform` key for the cache. The issue is that it's faster (and much simpler) just to build for both archs at the same time and let Xcode package them into a Universal Binary than it would be to matrix it and then combine (and sign) later.

**Review by roop — APPROVED** [review]
@jamilbk 👍🏻 The Apple CI runs where there are no changes to `swift/` should be very fast now because it wouldn't have to compile any Swift code.

Should we also include `rust/targets` in the cache here because the Swift build process includes building connlib?

**Comment by jamilbk** [comment]
> Should we also include rust/targets in the cache here because the Swift build process includes building connlib?
@roop Rust has its own cache so we _should_ be good there.

**Pull request merged**
