### PR TITLE
Fix test mode stats push failures and and test env issues

### PR DESCRIPTION
**Pull request by jamilbk**
WIP

### CODE REVIEW

**Comment by princemaple** [comment]
Can we split the nif out into a separate lib? That way get a signature open source library, and we don't have to further extend our CI time. A good example is https://github.com/adoptoposs/mjml_nif. The nif can be pre-compiled in the [CI](https://github.com/adoptoposs/mjml_nif/blob/main/.github/workflows/release.yml) and the lib consumer don't have to have rust toolchain installed (and don't have to spend the time compiling it).

**Comment by jamilbk** [comment]
> Can we split the nif out into a separate lib? That way get a signature open source library, and we don't have to further extend our CI time. A good example is https://github.com/adoptoposs/mjml_nif. The nif can be pre-compiled in the [CI](https://github.com/adoptoposs/mjml_nif/blob/main/.github/workflows/release.yml) and the lib consumer don't have to have rust toolchain installed (and don't have to spend the time compiling it).

Yeah, @akrousset proposed this as well as we were working through some of this stuff this afternoon. I think that's a good idea! Could also publish it to Hex.pm.

**Comment by jamilbk** [comment]
Closing this to focus on just fixing the tests.

**Comment by princemaple** [comment]
👍

**Pull request closed without merging**
