### PR TITLE
refactor(connlib): move `Tun` implementations out of `firezone-tunnel`

### PR DESCRIPTION
**Pull request by thomaseizinger**
The different implementations of `Tun` are the last platform-specific code within `firezone-tunnel`. By introducing a dedicated crate and a `Tun` trait, we can move this code into (platform-specific) leaf crates:

- `connlib-client-android`
- `connlib-client-apple`
- `firezone-bin-shared`

Related: #4473.

### CODE REVIEW

**Comment by thomaseizinger** [comment]
@ReactorScram I think this opens up some nice simplifications around WinTUN. Specifically, I think we can now make `TunDeviceManager` install / verify the DLL, and initialise the adapter within `TunDeviceManager::new` and pass the required things to `Tun::new` when creating it.

**Comment by thomaseizinger** [comment]
It is a bit painful to iterate on the Windows code with CI. @ReactorScram could you do me a favor and spend some cycles on this to fix the unit test? Thank you 🙏

**Comment by ReactorScram** [comment]
👍 I have https://github.com/firezone/firezone/pulls/assigned/ReactorScram bookmarked as a todo list, so I assigned both of us to this PR so it'll show up in my list and I'll remember to test / review it

**Review by conectado — APPROVED** [review]
Looks good to me :)

**Comment by thomaseizinger** [comment]
> 👍 I have https://github.com/firezone/firezone/pulls/assigned/ReactorScram bookmarked as a todo list, so I assigned both of us to this PR so it'll show up in my list and I'll remember to test / review it

Thanks! I promise I'll get around to setting up a Windows VM eventually.

**Comment by ReactorScram** [comment]
@thomaseizinger The test passes if you run it by itself. I think it's because 2 of the tests are running concurrently and fighting over the same tunnel device. I'll try to patch this.

I also noticed that the wintun DLL is getting embedded twice 😬 Made a task here so I don't forget https://github.com/firezone/firezone/issues/5977

**Pull request merged**
