### PR TITLE
refactor(docs): Update SECURITY.md to mention opening GitHub security advisories

### LINKED ISSUE #3786: SECURITY.md checkup
#### Describe the bug

- This URL doesn't load for me (Edit: It took a minute or so to load. Another time it waited 2 minutes, then gave me a proxy error.) - https://pgp.mit.edu/pks/lookup?op=get&search=0x45113BA04AD83D8A
- I'd like to send a test email to the security address at some random time and make sure someone gets it
- When I open a new issue, Github offers a "Report a security vulnerability" option which is contrary to SECURITY.md saying not to open a Github issue. I don't know if this is something we can control?
- I'm getting an error from GPG and can't figure out how to encrypt a message to the given pubkey:

```
gpg: key 4AD83D8A: no valid user IDs
gpg: this may be caused by a missing self-signature
gpg: Total number processed: 1
gpg:           w/o user IDs: 1
```

#### To Reproduce

N/A

#### Expected behavior

N/A

#### Screenshots / Logs

N/A

#### Platform (please complete the following information)

- _Component (i.e. macOS client / Linux client / Gateway / Admin portal):_
- _Firezone Version (e.g. 1.0.0 or N/A):_
- _OS and version: (e.g. Ubuntu 22.04 or N/A):_
- _Deployment method: (e.g. Docker / Systemd / App Store or N/A):_

#### Additional context

_Add any other context about the problem here._

### PR DESCRIPTION
**Pull request by jamilbk**
fixes #3786

### CODE REVIEW

**Review by ReactorScram — APPROVED** [review]
This is better but I'm still getting that GPG error:

```
gpg: key 4AD83D8A: no valid user IDs
gpg: this may be caused by a missing self-signature
gpg: Total number processed: 1
gpg:           w/o user IDs: 1
```

**Comment by jamilbk** [comment]
@ReactorScram Give it a shot now.

**Comment by ReactorScram** [comment]
@jamilbk I got the key to import in WSL, Cygwin's GPG didn't know how to handle it.

But the email address doesn't match, the key says firez.one. I just sent an encrypted test email to at firezone.dev.

**Comment by jamilbk** [comment]
@ReactorScram Hmm maybe something's off with your setup?

This is inside a fresh Debian 12 docker container, only `gnupg2` installed:

```
root@ff149f5f6d26:/# gpg --keyserver keyserver.ubuntu.com --recv-keys 250F8B56804107042DFC6A7345113BA04AD83D8A
gpg: key 45113BA04AD83D8A: public key "Firezone Security <security@firezone.dev>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

**Comment by ReactorScram** [comment]
@jamilbk Oh yeah I see both emails now, maybe I missed one earlier 👍 
image

**Pull request merged**
