### PR TITLE
chore(connlib): remove STUN-only functionality

### PR DESCRIPTION
**Pull request by thomaseizinger**
With this PR, we ignore all "stun" relays sent from the portal.

Follow-up from: #3353.

### CODE REVIEW

**Comment by thomaseizinger** [comment]
> With this PR, we ignore or "stun" relays sent from the portal.

cc @AndrewDryga I am not sure if the portal still supports that but after this PR, we can remove it!

**Comment by thomaseizinger** [comment]
I need to think about how we want to migrate the `snownet` tests.

**Comment by jamilbk** [comment]
We may want to hold on merging any risky refactors while we work to stabilize things for GA. I think there's quite a bit of cleanup in the portal to remove the user facing piece of the STUN-only feature, today it's just being hidden.

**Comment by jamilbk** [comment]
I'm surprised the integration tests pass if this is a breaking API change?

**Comment by thomaseizinger** [comment]
> I'm surprised the integration tests pass if this is a breaking API change?

I've left the messages there so we can still parse the STUN server but just ignore it.

**Comment by thomaseizinger** [comment]
Outdated.

**Pull request closed without merging**
