### PR TITLE
feat(windows): add aarch64 target

### PR DESCRIPTION
**Pull request by ReactorScram**
This will be tough because Github's free runners all appear to be x64, and cross-compiling on Windows is difficult. I couldn't get it to cross locally. But maybe we'll get lucky.

Edit: We got lucky. The only real barrier to cross-compiling is ring 0.16. I forked rcgen and x509-parser to get them up to ring 0.17, then I made a new branch in Firezone's webrtc fork to use those dependencies. Maybe the Cargo.toml [patch] table could do this without all the forks? I'm not sure.

Also it doesn't build MSIs for aarch64, which is fine for testing. I'll need to somehow re-enable MSIs for just x86_64 before it goes to customers.

### CODE REVIEW

**Comment by conectado** [comment]
for x509-parser there seems to be already a patch rusticata/x509-parser#148 and `rcgen` already depends on 0.17

>  Maybe the Cargo.toml [patch] table could do this without all the forks? I'm not sure.

In theory... you could just add, in this project, `ring = 0.17` to the patch section... however `patch` needs to point to a different source 🙃 but I think you can get away by pointing to the tag in the git repository for ring

**Review by conectado — APPROVED** [review]

**Comment by ReactorScram** [comment]
@conectado I'll see if I can do those before merging it, so that it's not pointing to repos in my personal Github

**Comment by ReactorScram** [comment]
@conectado Since that patch isn't in the official repo I had to change the URL too, and it feels weird. If Jamil can get it to build on his aarch64 system then I might just drop it

**Comment by ReactorScram** [comment]
We'll probably close this and just keep the DLL in without updating `ring`

**Comment by jamilbk** [comment]
Superseded by #2985

**Comment by ReactorScram** [comment]
Superseded by #2989, right?
I'll use this as a reference for a bit. I have a local copy but this way I don't have to do `git checkout`

**Comment by jamilbk** [comment]
@ReactorScram Ah yes

**Comment by ReactorScram** [comment]
x509-parser updated their `ring` dep https://github.com/rusticata/x509-parser/pull/148

**Pull request closed without merging**
