### PR TITLE
Properly set parent span ids for phoenix channels

### PR DESCRIPTION
**Pull request by AndrewDryga**

### CODE REVIEW

**Comment by thomaseizinger** [comment]
Where would I set the span as part of the phoenix channel? Is that a separate attribute in the Websocket payload?

**Comment by AndrewDryga** [comment]
@thomaseizinger we should support W3C trace headers (eg. `traceparent`), so you should set those for WS HTTP(s) request.

I think you will love the result, we will see a trace which starts at relay and shows everything that happened in the control plane from there :).

**Comment by thomaseizinger** [comment]
> @thomaseizinger we should support W3C trace headers (eg. `traceparent`), so you should set those for WS HTTP(s) request.

But once the WebSocket connection is established, there is no more place to set a header?

> I think you will love the result, we will see a trace which starts at relay and shows everything that happened in the control plane from there :).

Yep, looking forward to that!

If we wanted to, we could do the same thing for the client and propagate `spanIds` via STUN fields to the relay. Wouldn't work for data channels though.

**Comment by AndrewDryga** [comment]
@thomaseizinger you can only set it when it's established, from there we can see it spans the same trace. I feel like it's good enough because we can see spans ordered by timestamps plus some nesting, but if it will be not enough - we can add websocket message payload to further extend the integration.

> If we wanted to, we could do the same thing for the client and propagate spanIds via STUN fields to the relay. Wouldn't work for data channels though.

That was my end goal TBH, I know it will get hard to debug stuff in production so really wanted to have end-to-end traces as much as possible. Later we can also use reserved space of wireguard packets to propagate span ids in the data channels.

**Comment by thomaseizinger** [comment]
> @thomaseizinger you can only set it when it's established, from there we can see it spans the same trace. I feel like it's good enough because we can see spans ordered by timestamps plus some nesting, but if it will be not enough - we can add websocket message payload to further extend the integration.

I'll have to see how I can make that work. That span would never "end" on my end because I keep the connection alive for the entirety of the program. I don't think spans are sent until the actually end?

**Comment by AndrewDryga** [comment]
I think they should render nicely once all spans are submitted, but yes - we might have a delay to see a consistent data.

The downside that I care about more is that we will have very longs spans making Cloud Trace graph less usable.

**Pull request merged**
