### PR TITLE
docs: remove known issue re: gui restart

### PR DESCRIPTION
**Pull request by jamilbk**
based off #5932 to avoid conflicts.

### CODE REVIEW

**Review by ReactorScram — CHANGES_REQUESTED** [review]
Technically you still have to restart it, it just shows an error message reminding you.

Sort of like the "Firefox / Chrome has updated in the background and must be restarted" if you update them through a package manager and then open a new tab.

If we don't have space in the backlog for polishing that (infinite backlogs do suck) then we can say wontfix and this is fine

**Review by ReactorScram — APPROVED** [review]
Actually I'll make it Approve since it's not auto-merge, I just wanted that last part to be known

**Comment by jamilbk** [comment]
Ah I see. Thanks for clarifying. "You must restart" seems good enough 👍

**Comment by ReactorScram** [comment]
We can replace it with this so there isn't confusion of why we have a known issue that's closed on GitHub and preserved in the docs https://github.com/firezone/firezone/issues/5952

**Comment by jamilbk** [comment]
Updated to use new issue link.

**Review by ReactorScram — APPROVED** [review]

**Pull request merged**
