### PR TITLE
feat(android): add settings button to the session view

### PR DESCRIPTION
**Pull request by jasonboukheir**
Adds a `Settings` button similar to the sign in view:
Screenshot_20240224_120508

Then, while signed in, there is a warning dialog when the user attempts to "save" their settings:
Screenshot_20240224_120724

### CODE REVIEW

**Comment by jasonboukheir** [comment]
Fixes #3698

**Comment by jasonboukheir** [comment]
I decided to make the `Settings` button similar to the sign in view, since that spot is familiar to the user. It prioritizes consistency across both views, and requires minimal changes.

If we want to change the UX of the settings button while signed in, I think we should also change the settings button in the sign in view to match in order to maintain consistency.

**Review by ReactorScram — APPROVED** [review]

**Review by jamilbk — APPROVED** [review]
LGTM, nice work

**Comment by jamilbk** [comment]
@jasonboukheir Conflicts

**Pull request merged**
