### PR TITLE
Fix java method signature bug

### LINKED ISSUE #2706: Make "Advanced Settings" UI consistent on Android/ChromeOS
Match the Apple client UX

### LINKED ISSUE #2707: Add clear logs button on Android
Provide the ability for Android / ChromeOS clients to wipe the log directory from the "Advanced" pane of the Android/ChromeOS Settings screen.

### LINKED ISSUE #2722: Log android app logs to log directory as well
It would be useful if the Android clients also logged to the same log directory as connlib, perhaps under the app/ subfolder.

E.g.

`/data/data/dev.firezone.firezone/caches/logs/app`

- [ ] Logging calls in the app should log to both logcat and the above path
- [ ] Logs written to disk should be in JSON format similar to the existing connlib logs
- [ ] Test to ensure that "Export logs" also zips up this directory.

### PR DESCRIPTION
**Pull request by jamilbk**
Fixes a bug introduced in the DNS stuff

### CODE REVIEW

**Comment by jamilbk** [comment]
@ReactorScram This should fix the Android bug. After this is merged, you can build a new client for internal testing by manually running the "Kotlin" workflow from the Actions tab (similar to how we do it for the Apple client). That'll push a new release to Firebase

**Review by ReactorScram — APPROVED** [review]
LGTM. No easy way to make CI check this?

**Comment by ReactorScram** [comment]
Okay I'll merge this in and see if I can get a new release to my phone

**Comment by ReactorScram** [comment]
I got the new version installed but the problem I was having was not with DNS, it was with auth. When I try to sign in, Chrome gets stuck at app.firez.one and says "Not Found". I think the app link redirect isn't working. It'll probably be fixed when the auth change lands

**Comment by jamilbk** [comment]
Ah interesting. That happens if there's an applink issue, yeah it'll be resolved when we use the new auth scheme

**Pull request merged**
