### PR TITLE
Fix google redirect uri

### PR DESCRIPTION
**Pull request by jamilbk**
- Make docs consistent around redirect URIs
- Bump deps

### CODE REVIEW

**Review by princemaple — APPROVED** [review]
I hope there isn't one that requires **NO** trailing slash...

**Comment by princemaple** [comment]
Wait a minute... My test setup didn't have a trailing slash and it was fine. Are we sure it's a problem?

image

**Comment by jamilbk** [comment]
@princemaple Hmm -- I think it just needs to be consistent everywhere. See https://firezone-users.slack.com/archives/C02PV412LGZ/p1656493482293959

**Review by princemaple — APPROVED** [review]
The problem is caused by their provider config not matching their firezone config, right? Just want to be really clear - not that it requires a trailing slash or not.

**Review by princemaple — APPROVED** [review]
~~The problem is caused by their provider config not matching their firezone config, right? Just want to be really clear - not that it requires a trailing slash or not.~~

Huh, GitHub was giving me 500.

**Pull request merged**
