### PR TITLE
feat(ci): Add `swift-format` to apple build

### LINKED ISSUE #2157: Swift static analysis
Add a Swift linter to the CI pipeline to enforce sane style guide going forward.

### PR DESCRIPTION
**Pull request by jamilbk**
Was doing some CI work and thought I would clean up our Swift codebase a little.

- Moves `CallbackHandler.swift` to `swift/apple` so it's subject to style enforcement
- Adds `swift-format lint --strict` build step to catch style issues in Xcode (and CI)
- Ran `swift-format -i` on all files to reset formatting
- Fixed any warnings found

Fixes #2157

### CODE REVIEW

**Comment by jamilbk** [comment]
Fixing a few linting issues

**Review by roop — APPROVED** [review]
Thanks for taking this up.

Looks good, LGTM.

A minor issue: Since CallbackHandler.swift has moved, it should be removed from `swift/apple/FirezoneNetworkExtension/Connlib.xcfilelist` as well.

**Comment by roop** [comment]
I'll fix the `Connlib.xcfilelist` in a subsequent PR.

**Comment by jamilbk** [comment]
> A minor issue: Since CallbackHandler.swift has moved, it should be removed from `swift/apple/FirezoneNetworkExtension/Connlib.xcfilelist` as well.

It actually moved into that directory, so I think the file list is actually valid?

**Comment by roop** [comment]
The `Connlib.xcfilelist` specifies which files are copied from `rust/connlib/clients/apple` in the build process. This is to make peace with the Xcode build system, telling it that this file might be missing now, but it's okay because it will be created during the build.

**Comment by jamilbk** [comment]
Ah, got it. Thanks for clarifying

**Pull request merged**
