### PR TITLE
chore(gui-client): delete GTK+ and Iced prototypes

### PR DESCRIPTION
**Pull request by ReactorScram**
We don't need these since Tauri v2 looks like it's about to succeed, and keeping packages outside of the workspace has been breaking dependabot PRs

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]
Send it!

**Comment by thomaseizinger** [comment]
@jamilbk Needs update of required jobs.

**Comment by jamilbk** [comment]
> @jamilbk Needs update of required jobs.

done

**Comment by thomaseizinger** [comment]
@ReactorScram It seems that something is wrong with your local Git setup because the commits aren't signed.

**Comment by ReactorScram** [comment]
@thomaseizinger Yeah it's the new Ubuntu 22.04 dev VM I made for Tauri v2. Thanks for catching that

**Pull request merged**
