### PR TITLE
Fix outdated mock

### PR DESCRIPTION
**Pull request by princemaple**
Make master green again!

#590

### CODE REVIEW

**Comment by jamilbk** [comment]
@princemaple Thanks! I was just working on a fix as well but you beat me to it. That's what I get for rushing a release out the door 🙃

**Review by jamilbk — APPROVED** [review]

**Comment by princemaple** [comment]
I've tagged all the PRs. I'll look at TOTP next week, that sounds good to you?

**Comment by jamilbk** [comment]
> I've tagged all the PRs. I'll look at TOTP next week, that sounds good to you?

Cool thanks. For TOTP, maybe it's better to start with email-based 2FA? We're still verifying how important TOTP-based 2FA is since many OIDC providers already include it as part of their auth flow, so it may be redundant.

**Comment by princemaple** [comment]
Sure. Let me know if you there are other more important things.

**Pull request merged**
