### PR TITLE
chore(ci): Use GH actions cache for Tauri builds

### LINKED ISSUE #3456: tauri build in CI doesn't seem to be using the Rust cache
https://github.com/firezone/firezone/actions/runs/7729393371/job/21072455959#step:5:522

### PR DESCRIPTION
**Pull request by jamilbk**
Builds off #3905 and uses the GH actions cache for tauri builds in order to get around the `crate-type` problem sccache has with Tauri apps.

Fixes #3456

### CODE REVIEW

**Comment by jamilbk** [comment]
Getting a strange CI failure for the Apple builds. We've seen this before: https://github.com/firezone/firezone/issues/2443

Will see if I can uncover root cause. Maybe it's the way DNS is configured on the `macos-14` runners.

**Review by ReactorScram — APPROVED** [review]
Makes sense, hope it works

**Review by thomaseizinger — APPROVED** [review]
Let's try it!

**Comment by jamilbk** [comment]
Gah, finally fixed the issues on Apple. It's because we were unsetting some of the env vars being used by the `rustc` sccache wrapper, and apparently it was a race condition that wasn't triggered before this PR (nothing relevant changed to cause this)

**Pull request merged**
