### PR TITLE
Bump chef client in firezone cookbooks Gemfile to 17.10.0

### LINKED ISSUE #744: Bump chef infra client
Current version is EOL.

### PR DESCRIPTION
**Pull request by akrousset**
Fixes #744

### CODE REVIEW

**Comment by jamilbk** [comment]
💯

**Review by jamilbk — DISMISSED** [review]
Lgtm ready to merge if tests pass

**Comment by akrousset** [comment]
Cool, just had to rebase it real quick :)

**Review by jamilbk — APPROVED** [review]

**Comment by akrousset** [comment]
🤦 must've accidentally saved an undo before updating the branch and sign my commits!

**Pull request merged**
