### PR TITLE
chore: move markdown files into `docs/` directory

### PR DESCRIPTION
**Pull request by thomaseizinger**
Apart from the LICENSE, GitHub supports detecting all of these files also within a `docs/` directory. This includes the README!

### CODE REVIEW

**Comment by thomaseizinger** [comment]
You can see that this works by viewing the branch directly: https://github.com/firezone/firezone/tree/feat/docs-directory

**Comment by jamilbk** [comment]
There a few more places where we link to these that need updating. Here are the ones I can remember:

```
website/src/components/FAQ/readme.mdx|232 col 86| [Read our security disclosure policy](https://github.com/firezone/firezone/blob/main/SECURITY.md)
website/src/app/docs/deploy/security-considerations/readme.mdx|61 col 85| [our security bug reporting policy ](https://github.com/firezone/firezone/blob/main/SECURITY.md).
elixir/mix.exs|19 col 32| extras: ["README.md", "SECURITY.md", "CONTRIBUTING.md"]
scripts/README.md|26 col 19| [CONTRIBUTING](../CONTRIBUTING.md#pre-commit).
website/src/app/docs/readme.mdx|54 col 2| [CONTRIBUTING.md](https://github.com/firezone/firezone/blob/main/CONTRIBUTING.md).
website/src/app/docs/readme.mdx|54 col 66| [CONTRIBUTING.md](https://github.com/firezone/firezone/blob/main/CONTRIBUTING.md).
rust/connlib/tunnel/src/device_channel/tun_darwin.rs|96 col 71| // Credit to Jason Donenfeld (@zx2c4) for this technique. See NOTICE.txt for attribution.
```

**Comment by thomaseizinger** [comment]
> website/src/components/FAQ/readme.mdx|232 col 86| [Read our security disclosure policy](https://github.com/firezone/firezone/blob/main/SECURITY.md)
> website/src/app/docs/deploy/security-considerations/readme.mdx|61 col 85| [our security bug reporting policy ](https://github.com/firezone/firezone/blob/main/SECURITY.md).

For these two, would it be better to link to the "tab" instead? https://github.com/firezone/firezone/tree/feat/docs-directory?tab=security-ov-file

That would be slightly more stable.

**Comment by thomaseizinger** [comment]
> elixir/mix.exs|19 col 32| extras: ["README.md", "SECURITY.md", "CONTRIBUTING.md"]

Is there a way we can make the build fail if those are not there?

**Comment by thomaseizinger** [comment]
> There a few more places where we link to these that need updating. Here are the ones I can remember:
> 
> ```
> website/src/components/FAQ/readme.mdx|232 col 86| [Read our security disclosure policy](https://github.com/firezone/firezone/blob/main/SECURITY.md)
> website/src/app/docs/deploy/security-considerations/readme.mdx|61 col 85| [our security bug reporting policy ](https://github.com/firezone/firezone/blob/main/SECURITY.md).
> elixir/mix.exs|19 col 32| extras: ["README.md", "SECURITY.md", "CONTRIBUTING.md"]
> scripts/README.md|26 col 19| [CONTRIBUTING](../CONTRIBUTING.md#pre-commit).
> website/src/app/docs/readme.mdx|54 col 2| [CONTRIBUTING.md](https://github.com/firezone/firezone/blob/main/CONTRIBUTING.md).
> website/src/app/docs/readme.mdx|54 col 66| [CONTRIBUTING.md](https://github.com/firezone/firezone/blob/main/CONTRIBUTING.md).
> rust/connlib/tunnel/src/device_channel/tun_darwin.rs|96 col 71| // Credit to Jason Donenfeld (@zx2c4) for this technique. See NOTICE.txt for attribution.
> ```

I think I fixed all of them. I did a search with `rg` for each file and they didn't turn up anywhere else! I also added a linter to at least catch local reference.

If we want, we can also use a cronjob to constantly check for dead links, that would probably also catch the ones deployed to the website etc. See https://github.com/lycheeverse/lychee-action?tab=readme-ov-file#usage.

**Comment by jamilbk** [comment]
> > website/src/components/FAQ/readme.mdx|232 col 86| [Read our security disclosure policy](https://github.com/firezone/firezone/blob/main/SECURITY.md)
> 
> > website/src/app/docs/deploy/security-considerations/readme.mdx|61 col 85| [our security bug reporting policy ](https://github.com/firezone/firezone/blob/main/SECURITY.md).
> 
> 
> 
> For these two, would it be better to link to the "tab" instead? https://github.com/firezone/firezone/tree/feat/docs-directory?tab=security-ov-file
> 
> 
> 
> That would be slightly more stable.

👍🏼

**Review by jamilbk — APPROVED** [review]

**Comment by thomaseizinger** [comment]
> > > website/src/components/FAQ/readme.mdx|232 col 86| [Read our security disclosure policy](https://github.com/firezone/firezone/blob/main/SECURITY.md?rgh-link-date=2024-02-27T01%3A10%3A27Z)
> > 
> > 
> > > website/src/app/docs/deploy/security-considerations/readme.mdx|61 col 85| [our security bug reporting policy ](https://github.com/firezone/firezone/blob/main/SECURITY.md?rgh-link-date=2024-02-27T01%3A10%3A27Z).
> > 
> > 
> > For these two, would it be better to link to the "tab" instead? [`feat`/docs-directory?tab=security-ov-file](https://github.com/firezone/firezone/tree/feat/docs-directory?tab=security-ov-file&rgh-link-date=2024-02-27T01%3A10%3A27Z)
> > That would be slightly more stable.
> 
> 👍🏼

I ended up linking to the actual file. The link to the tab will take people to GitHub instead where it might not be obvious that the should look at the rendered MD.

**Pull request merged**
