### PR TITLE
fix(windows): DNS changes during sign-in and sign-out

### PR DESCRIPTION
**Pull request by ReactorScram**
Relating to #2713 

Right now when you sign out, even though the tunnel adapter is torn down, Windows has still cached the tunnel's DNS responses, and curl hangs trying to reach a 100.x.x.x CGNAT address.

Closing the client seems to cause Windows to immediately invalidate the DNS cache, and then curl goes back to the normal DNS easily. It's signing out that's a problem.

Also signing in takes a while, that will be a separate issue.

### CODE REVIEW

**Comment by ReactorScram** [comment]
`ipconfig /flushdns` is what Tailscale does. I don't know if we need `ipconfig /registerdns`, this is related to Active Directory and I don't know much about AD.

`/flushdns` returns almost instantly, but it takes another 10-15 seconds before curl will work again. It doesn't get the CGNAT address, it just hangs somewhere. Something in Windows is probably still waiting on some timeout:

image

**Comment by ReactorScram** [comment]
This might be caused by #2975 

If the whole process exits, that closes the tunnel, and `curl` instantly gets the real IPs again.

The only problem is that adding routes is slow on Windows, so during startup there's a long period when curl gets the real IPs when it should be getting the CGNAT tunneled IPs

**Comment by jamilbk** [comment]
@ReactorScram I think we can close this issue for the time being since we've determined it may not be an issue per se with the Windows client?

**Comment by ReactorScram** [comment]
@jamilbk Agreed, the "DNS caching on sign-out" I saw was probably #2975

**Pull request closed without merging**
