### PR TITLE
Update alpine version to match one available for hexpm/elixir

### PR DESCRIPTION
**Pull request by leriel**
Hello and thanks for this awesome project!

I want to mention that update to dockerfiles that came in yesterday broke the Dockerfile.prod, because hexpm/elixir image does not exist with current combination of versions

https://github.com/firezone/firezone/commit/ea67535f9ab5a57b4a703213704931de6f86a7c5

Current combination:
```
ARG ELIXIR_VERSION=1.13.4
ARG OTP_VERSION=25.0.4
ARG ALPINE_VERSION=3.16.0

ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-alpine-${ALPINE_VERSION}"
```
resolves to image `hexpm/elixir:1.13.4-erlang-25.0.4-alpine-3.16.0` which does not exist. To use OTP 25.0.4, alpine version would need to be bumped to 3.16.1: https://hub.docker.com/layers/hexpm/elixir/1.13.4-erlang-25.0.4-alpine-3.16.1/images/sha256-45b098fb2edaa955ea6f811cf3cf224d870a457edfca763b3539d04d75927638?context=explore

This pull request does just that

### CODE REVIEW

**Comment by jamilbk** [comment]
Thanks for the revert! Totally didn't think anyone was even using our Docker image since it's not documented yet (coming in #913)

**Comment by leriel** [comment]
Thanks for accept! I very much am using the docker image :) It was actually an upgrade of alpine rather than downgrade of OTP - latter was my first reaction, but i took glance at available images and saw i can help move things forward instead of reverting :)

**Comment by princemaple** [comment]
Missed it in review, as I've been working on my own branch and haven't really re-built my images.

**Comment by princemaple** [comment]
Glad to know someone is already using the docker image, though.

**Pull request merged**
