### PR TITLE
fix(gateway): re-implement resource address resolution in eventloop

### PR DESCRIPTION
**Pull request by conectado**
Reimplements what #3654 reverted with a fix

### CODE REVIEW

**Review by ReactorScram — COMMENTED** [review]
I'll approve it in a few minutes if the DNS CI test looks good. I've skimmed through the Rust code already but I can't really follow it.

**Review by ReactorScram — APPROVED** [review]
The test passed, LGTM

**Review by jamilbk — APPROVED** [review]
Nice

**Comment by thomaseizinger** [comment]
Thank you for fixing my bug :)

**Pull request merged**
