### PR TITLE
Add ring to menubar icons; use brand neutral shades

### PR DESCRIPTION
**Pull request by jamilbk**
Updates the menubar icon to (1) add a ring for better visibility, (2) use the system status bar size of 22x22 with the icon itself constrained to 16x16 and (3) use the neutral brand colors from our brand palette in Figma. Also updates macOS icon with rounded corners and drop shadow to follow Apple's guidelines

@roop I'm sure I could be overlooking something -- let me know if these check out or violate any kind of design patterns I wasn't aware of.

## dark menubar disconnected
Screenshot 2023-07-20 at 9 05 34 PM

## dark menubar connected
Screenshot 2023-07-20 at 8 55 54 PM

## light menubar disconnected
Screenshot 2023-07-20 at 9 00 47 PM

## light menubar connected
Screenshot 2023-07-20 at 9 00 22 PM

## macOS icon with rounded borders and dropshadow
Screenshot 2023-07-20 at 11 09 39 PM

### CODE REVIEW

**Review by francesca64 — APPROVED** [review]

**Comment by roop** [comment]
I think it's hard to recognize the Firezone logo in the status bar with these icons (because the circle takes up space). So, I think the previous version was better. What do you think?

**Comment by jamilbk** [comment]
@roop The problem with simply changing the shade when connected is that different color wallpapers will affect the contrast of the shade. I was facing an issue where the dark mode disconnected icon was almost completely blended into the menubar, and didn't know Firezone was running because the pieces of the logo are too thin to stand out well on their own. So I was hoping to give it some more bulk.

Having two shapes to alternate the fill between with a ring around them seemed to solve the issue.

**Comment by jamilbk** [comment]
I can increase the filled up space inside the 22x22 icon to make the actual logo part bigger. Let me try that real quick.

**Comment by roop** [comment]
@jamilbk:

When the background is dark, the OS should use the dark-mode icons, which are meant to be light colour, so they can stand out in the dark background. But I do agree that sometimes, it might be too light to be visible.

~~In https://github.com/firezone/firezone-apple/pull/77/commits/4e810410d06db18e522f8becd7891723ee91b201, I had adjusted the shades for light and dark modes. Is it okay to try them out?~~ (They are part of this PR.)

One idea as an alternative for the ring is: For the logged out state, we can use a dark slash on top of a light firezone logo, like the macOS wifi and bluetooth status bar items:

Screenshot 2023-07-24 at 6 08 05 PM

**Comment by jamilbk** [comment]
> the OS should use the dark-mode icons

It was, but for a dark gray wallpaper they were tending to blend in due to menu bar transparency.

> One idea as an alternative for the ring is: For the logged out state, we can use a dark slash on top of a light firezone logo, like the macOS wifi and bluetooth status bar items:

Ah, that's a great idea. Would it be possible to use our brand neutral palette for these, or do they need to be strictly grayscale?

P.S. If you export the SVGs in Figma directly it looks like they're about 1/2 the file size. You should be added to the workspace.

**Comment by jamilbk** [comment]
@roop Updated them. Also I changed the colors to match what the other menubar icons were using. It seems they all use the same shades.

Screenshot 2023-07-24 at 6 52 39 AM

Screenshot 2023-07-24 at 6 52 32 AM

Screenshot 2023-07-24 at 6 52 08 AM

Screenshot 2023-07-24 at 6 52 03 AM

**Comment by jamilbk** [comment]
Can save further feedback for #1809

**Pull request merged**
