### PR TITLE
Update early access timeline, remove announcement banner

### PR DESCRIPTION
**Pull request by jamilbk**
- Update timeline to reflect revised estimates 😅 
- Remove announcement banner -- been up since August and felt it was getting stale / annoying

### CODE REVIEW

**Comment by jamilbk** [comment]
@jefferenced One of the cool things about our site on NextJS / Vercel is we can preview it and comment directly on the drafted site build using the [link in this comment](https://github.com/firezone/firezone/pull/2572#issuecomment-1790085551)

**Comment by jefferenced** [comment]
> Visit Preview

That's awesome, we had a similar feature 'view deployment' (preview) with Fly.io, so I'm very comfortable with this kind of setup!

**Review by jefferenced — CHANGES_REQUESTED** [review]
Suggest the following
* Hide/remove the "Join our community" section
* Remove the "Ready to get started?" section, or just "Copy and paste the command below on any Docker-supported host." and 'bash <(curl -fsSL https://github.com/firezone/firezone/raw/legacy/scripts/install.sh)'
* I think there's a great onramp to Firezone from the command line (starting with spinning up a gateway), but I'm not sure how far down that road we've gone.
* Change either "Contact Sales" or "Deploy now" to something like "Request early access" and send people to https://www.firezone.dev/product/early-access

**Review by AndrewDryga — APPROVED** [review]

**Comment by jamilbk** [comment]
@jefferenced Thanks for the feedback, updated!

**Review by jefferenced — APPROVED** [review]

**Comment by jamilbk** [comment]
Refs #2519

**Pull request merged**
